---
title: "Random forest"
author: "Wasim Syed"
date: "2024-03-20"
output: html_document
---

## Colors

```{r}
################## Colors

#VAX SIG DB
ann_vaxsig_colors = list(
  type = c("VLP" = "#D7B0EE",
           "LA" =  "#5e60ce",
           "CONJ" = "#015BA0", 
           'IN'= "#76c893", #1st Gen  vaccines
           'VV' = "#5e60ce", #3rd Gen vaccines
           'RNA' = "#56cfe1",
           'SU' = "#b5e48c",
           'I'= "#f72585",
           "H" = "grey95"),
  target_pathogen_disease = c('MENINGOCOCCUS'	= "#16E0BD",
                             'PNEUMOCOCCUS'	= "#44C199",
                             'TUBERCULOSIS'	= "#99e2b4",
                             'F TULARENSIS'	= "#90e0ef",
                             'LEISHMANIA'	= "#118ab2",
                             'MALARIA' = "#015BA0",
                             'EBOV'	= "#5e60ce",
                             'HBV'	= "#D7B0EE",
                             'HBV, HAV'	= "#D7B0EE",
                             'HIV'	= "#b5179e",
                             'HPV'	= "#c77dff",
                             'INFLUENZA'	= "#deaaff",
                             'MEASLES'	= "#9d4edd",
                             'MMR'	= "#7b2cbf",
                             'SMALLPOX'	= "#e5b3fe",
                             'VEEV'	= "#ecbcfd",
                             'VZV'	= "#c8b6ff",
                             'YF'	= "#b8c0ff"),
  covid_other = c("COVID" = "#56cfe1",
                  "OTHER" = "#343a40"),
  microbe_type = c("VIRUS" = "#5e60ce",
                   'BACTERIUM' = "#72efdd",
                   'PARASITE' = "#b5179e"),
  
  week = c("0" = "#ECF8FA",
           "1" = "#caf0f8",
           "2" = "#6CD5EA",
           "3" = "#0087BF",
           "4" = "#015BA0", 
           "6" = "#03045e",
           "7" = "#03045e",
           "8" = "#03045e"),
  month = c("1" = "#caf0f8",
            "0" = "#6CD5EA",
           "2" = "#015BA0"),
  vaccine = c("BBIBP" = "#76c893",
  "ZF2001" = "#b5e48c",
  "BNT" = "#56cfe1",
  "MO" = "#72ddf7",
  "ChAd" = "#5e60ce",
  "I" = "grey95",
  "H" = "grey95"),
  dose = c(
            "0" = "grey95",
            "1" = "#56cfe1",
            "2" = "#5978d4",
            "3" = "#b5179e"),
  day = c(
          "0" = "white",
          "1" = "#caf0f8",
          "2" = "#ade8f4",
          "3" = "#90e0ef",
          "4" = "#6CD5EA",
          "5" = "#48cae4",
          "6" = "#00b4d8",
          "7" = "#0096c7",
          "10" = "#0087BF",
          "11" = "#0087BF",
          "14" = "#0077b6",
          "26" = "#015BA0",
          "28" = "#023e8a",
          "51" = "#03045e"),
  type = c('IN'= "#343a40", #1st Gen  vaccines
           'SU' = "#00a896",
           'VV' = "#72efdd", #3rd Gen vaccines
           'RNA' = "#56cfe1",
           'SU' = "#b5179e",
           'I'= "#da1e37",
           "H" = "grey95"), 
  infection = c("0" = "#64dfdf",
                "1" = "#f72585",
                "2" = "#a4161a"),
  variant = c("None" = "grey95",
              "Beta" = "#72efdd",
              "Omicron" = "#5e60ce"),
  severity = c("H" = "grey95",
               "S" = "#b5179e",
               "MO" = "#5e60ce",
               "MI" = "#80ffdb",
               "NA" = "grey95"),
  sex = c("Male" = "#56cfe1",
          "Female" = "#b5179e",
          "M/F" = "#5e60ce"),
  disease_vac = c("I" = "#5e60ce",
                  "V" = "#64dfdf")
  )


col_process_notimmune = list(
  "1" = c("Cellular" = "#5e60ce",
        "Interspecies interaction" = "#88d4ab",
        "Metabolism" = "#48cae4",
        "Reg. of BP" = "#f72585",
        "."="white"),
  "2" = c("Cellular" = "#5e60ce",
        "Interspecies interaction" = "#88d4ab",
        "Metabolism" = "#48cae4",
        "Reg. of BP" = "#f72585",
        "."="white"),
  "3" = c("Cellular" = "#5e60ce",
        "Interspecies interaction" = "#88d4ab",
        "Metabolism" = "#48cae4",
        "Reg. of BP" = "#f72585",
        "."="white"),
  "4" = c("Cellular" = "#5e60ce",
        "Interspecies interaction" = "#88d4ab",
        "Metabolism" = "#48cae4",
        "Reg. of BP" = "#f72585",
        "."="white"),
  "5" = c("Cellular" = "#5e60ce",
        "Interspecies interaction" = "#88d4ab",
        "Metabolism" = "#48cae4",
        "Reg. of BP" = "#f72585",
        "."="white"))


col_process_immune = list(
  "1" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELLS" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "2" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELLS" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "3" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "4" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "5" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "6" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "7" =c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "8" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "9" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"),
  "10" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
        "B CELL" = "#7b2cbf",
        "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
        "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
        "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
        "T CELL" = "#c77dff",
        "T HELPER CELLS" = "#c77dcc",
        "COMPLEMENT" = "#ffadc7",
        "ANTIVIRAL & IFN" = "#88d4ab",
        "ARPP" = "#14746f",
        "DENDRITIC CELL" = "#036666",
        "EOSINOPHIL" = "#67b99a",
        "INFLAMMATION" = "#99e2b4",
        "INNATE IMMUNE SYSTEM" = "#06d6a0",
        "MAST CELL" = "#56ab91",
        "MONOCYTE" = "#358f80",
        "NEUTROPHIL" = "#78c6a3",
        "NK CELL" = "#469d89",
        "MACROPHAGE" = "#14746f",
        "GENERAL" = "#343a40",
        "ANTIMICROBIAL" = "#48cae4",
        "."="white"))

ImmuneGO_Annotated_GO %>% filter(go_term == "Manual") %>% select(process) %>% distinct()

```



https://juliasilge.com/blog/sf-trees-random-tuning/
# Libraries
```{r}
install.packages("randomForest")
install.packages("caret")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("tidymodels")
install.packages("reticulate")
install.packages("themis")
install.packages("ranger")


library(tidymodels)
tidymodels_prefer()
library(randomForest)
library(ranger)
library(caret)
library(reticulate)
library(themis)
library(tidyverse)
library(rpart)
library(rpart.plot)
library(here)
library(ggrepel)
library(ComplexHeatmap)
library(janitor)
library(ggsci)
```


#Tidymodels
```{r}
# Input data ----
filename = "ImmuneGO_Genes"
outcomevar = "sex"
df = all_matrices_normalized_counts
ann_vaccines_samples = ann_vaccines_samples

#Select only important genes
PC1_2 = PC_1_2_cos2

# Prepare data ------

df_input <- df %>%
  rownames_to_column("genes") %>%
  inner_join(PC1_2 %>% select(genes) %>% distinct(), by = "genes") %>%
  column_to_rownames("genes") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("sample") %>%
  inner_join(ann_vaccines_samples %>% select(sample,type, day, age, sex, dose), by = "sample") %>%
  select(sample, type, everything()) %>%
  column_to_rownames("sample") %>%
  mutate_if(is.character, factor)

glimpse(df_input)

# Split data
set.seed(123)  
split <- initial_split(df_input, prop = 0.7, strata = "type")
trees_train <- training(split)
trees_test <- testing(split)

# Create recipe
tree_rec <- recipe(type ~ ., data = trees_train) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_upsample(type) #Upsample unbalanced data

tree_prep <- prep(tree_rec)

juiced <- juice(trtree_prep)

# Set random forest hyper parameters
tune_spec <- rand_forest(
  mtry = tune(),
  trees = 2000,
  min_n = tune()
) %>%
  set_mode("classification") %>% 
  set_engine("ranger")

# Create workflow
tune_wf <- workflow() %>%
  add_recipe(tree_rec) %>%
  add_model(tune_spec)

#Cross validation
set.seed(234)
trees_folds <- vfold_cv(trees_train)

# Parallel computing 
doParallel::registerDoParallel()

set.seed(345)
tune_res <- tune_grid(
  tune_wf,
  resamples = trees_folds,
  grid = 20
)

# Assess data ----
# AUC
metrics_tuneres = tune_res %>%
  collect_metrics() %>%
  filter(.metric == "roc_auc") %>%
  select(mean, min_n, mtry) %>%
  pivot_longer(min_n:mtry,
    values_to = "value",
    names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_line() +
  geom_point(show.legend = FALSE) +
  geom_text_repel(aes(label = value))+
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "AUC")

ggsave(metrics_tuneres, file = paste0(outcomevar, "_tidymodels_tune_res.png"), width = 10, height = 6)

# Tune hyperparameters ----
rf_grid <- grid_regular(
  mtry(range = c(86,100)),
  min_n(range = c(7,11)),
  levels = 5
)

set.seed(456)
regular_res <- tune_grid(
  tune_wf,
  resamples = trees_folds,
  grid = rf_grid
)

# Assess performance -----
regular_res %>%
  collect_metrics() %>% 
  write.csv(file = paste("metrics_finalmodel_", outcomevar, today(), ".csv"), row.names = F)

ggsave(regular_res %>%
  collect_metrics() %>%
  filter(.metric == "roc_auc") %>%
  mutate(min_n = factor(min_n)) %>%
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha = 0.5, size = 1.5) +
  geom_point() +
  labs(y = "AUC"), file = paste("roc_auc_", outcomevar, today(), ".png"), width = 10, height = 6)

# Select best model -----
best_auc <- select_best(regular_res, metric = "roc_auc")
final_rf <- finalize_model(
  tune_spec,
  best_auc
)

library(vip)

final = final_rf %>%
  set_engine("ranger", importance = "permutation") %>%
  fit(type ~ .,
    data = juice(tree_prep)
  ) %>% 
  vip()

final

final %>% ggsave(file = paste0("vipgenes_tidymodels_", outcomevar, today(), ".png"))

genes_rf = final$data
genes_rf
genes_rf %>% write.csv(file = paste0("vipgenes_tidymodels_", outcomevar, today(), ".csv"), row.names = F)



importance_plot = ggplot(vipgenes_tidymodels_type2024_03_29) +
  aes(x = reorder(Variable, Importance),
    y = Importance,
    color = Importance,
      weight = Importance) +
  geom_segment(aes(x=Variable, xend=Variable, y=0, yend=Importance)) +
  geom_point(shape = "circle", size = 5) +
  theme_minimal() +
  xlab("Genes") + 
  ylab("Importance") +
  geom_text(aes(label = round(Importance, 4), y = Importance),
            hjust = -0.5, 
            size = 4,
            angle = 0,
            color = "black")+
  ylim(0, 0.035)+
  scale_color_gradient(low = "#4DBBD5FF", high = "#DC0000FF") +
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 90, vjust = 1, hjust=1, size = 12, color = "black"),
        axis.text.y = element_text(size = 12, angle = 0, color = "black"),
        panel.grid.minor.y = element_blank(),
        legend.text = element_text(size=12),
        legend.title = element_text(size = 12, face = "bold")) +
    coord_flip()

ggsave(importance_plot, file = paste0("vipgenes_tidymodels_", outcomevar, today(), ".png"), width = 8, height = 5)


```


```{r}
# Train final model with tuned hyperparameters
final_wf <- workflow() %>%
  add_recipe(tree_rec) %>%
  add_model(final_rf)

final_res <- final_wf %>%
  last_fit(split)

final_res %>%
  collect_metrics() %>% 
write.csv(file = paste0("rf_metrics", outcomevar, today(), ".csv"), row.names = F)

final_res %>%
  collect_predictions() %>%
  mutate(correct = case_when(
    type == .pred_class ~ "Correct",
    TRUE ~ "Incorrect"
  )) %>%
  bind_cols(trees_test)
```

### Heatmaps

#### Gene counts per sample
```{r}
# Heatmap with gene counts per sample 
all_matrices_normalized_counts

# Matrix
counts_imps = genes_rf %>% 
  select(genes = Variable) %>% 
  inner_join(all_matrices_normalized_counts %>% rownames_to_column("genes"), by = "genes") %>%
  pivot_longer(cols =-genes, names_to = "sample", values_to = 'counts') %>% 
  inner_join(ann_vaccines_samples, by = "sample") %>% 
  select(condition, samples = sample, counts, genes) %>% 
  pivot_wider(names_from = c("condition", "samples"), values_from = 'counts') %>% 
  column_to_rownames("genes") %>% 
  as.matrix() %>% 
  replace(is.na(.), 0)

#Annotations
colors_col = genes_rf %>% 
  select(genes = Variable, Importance) %>% 
  inner_join(all_matrices_normalized_counts %>% rownames_to_column("genes") %>% pivot_longer(cols = -genes, names_to = "sample", values_to = "counts"), by = "genes") %>%
  left_join(ann_vaccines_samples, by = "sample") %>%
  left_join(covid_others_colors %>% select(condition, color), by = "condition") %>% 
  select(sample, color) %>% 
  distinct() %>% 
  .$color

colors_row <- genes_rf %>% 
  select(genes = Variable, importance = Importance) %>% 
  inner_join(all_matrices_normalized_counts %>% rownames_to_column("genes") %>% pivot_longer(cols = -genes, names_to = "sample", values_to = "counts"), by = "genes") %>%
  select(genes, importance) %>%
  distinct() %>% 
  mutate(imp_color = circlize::colorRamp2(c(min(importance), max(importance)), c("white", "red"))(importance)) %>% 
  .$imp_color

head(counts_imps)
dim(counts_imps)
length(colors_col)
length(colors_row)


#Plot
png(paste0("randomforest_heatmap_conditions_counts_tidymodels_", outcomevar, today(), ".png"), units="in", width=10, height=10, res=300)
heatmap(counts_imps, 
        col = hcl.colors(100, palette = "reds", rev = T),
        ColSideColors = colors_col, 
        RowSideColors = colors_row, 
        scale = "row",
        margins = c(10, 10))
dev.off()

```

#### Gene L2FC per condition
```{r}
ImmuneGO_Annotated_Genes_all = ImmuneGO_Annotated_Genes_28_2_24 %>% 
  filter(!process %in% c("TCR REPERTOIRE", "BCR REPERTOIRE"))

ImmuneGO_Genes = all_degs_p_05_vac_infected_19_12_23 %>% 
  select(-"...1", -"...12") %>% 
  inner_join(ImmuneGO_Annotated_Genes %>% 
               select(genes, process) %>% 
               distinct() %>% 
               select(genes),
               by = "genes") %>% 
  distinct()

# Matrix
l2fc_imps = genes_rf %>% 
  select(genes = Variable, importance = Importance) %>% 
  inner_join(ImmuneGO_Genes, by = "genes") %>%
  select(genes, condition, log2fold_change) %>% 
  pivot_wider(names_from = condition, values_from = log2fold_change) %>% 
  column_to_rownames("genes") %>% 
  as.matrix() %>% 
  replace(is.na(.), 0)

#Annotations
colors_col = genes_rf %>% 
  select(genes = Variable, importance = Importance) %>% 
  inner_join(ImmuneGO_Genes, by = "genes") %>%
  inner_join(covid_others_colors %>% select(condition, color), by = "condition") %>% 
  select(condition,color) %>% 
  distinct() %>% 
  .$color

colors_row <- genes_rf %>% 
  select(genes = Variable, importance = Importance) %>% 
  inner_join(ImmuneGO_Genes, by = "genes") %>%
  select(genes, condition, log2fold_change, importance) %>% 
  pivot_wider(names_from = condition, values_from = log2fold_change) %>% 
  mutate(imp_color = circlize::colorRamp2(c(min(importance), max(importance)), c("white", "red"))(importance)) %>% 
  .$imp_color

#Plot
png(paste0("randomforest_heatmap_conditions_l2fc", outcomevar, today(), ".png"), units="in", width=10, height=10, res=300)
heatmap(l2fc_imps,
        col = hcl.colors(100, palette = "reds", rev = T),
        ColSideColors = colors_col, 
        RowSideColors = colors_row, 
        scale = "row",
        margins = c(10, 10))
dev.off()
```


```{r}
ImmuneGO_Annotated_Genes= `ImmuneGO_Annotated_Genes_2024-03-26`
outcomevar = "_Type_"

rf_genes = vipgenes_tidymodels_type2024_03_29 %>% 
  clean_names() %>% 
  select(genes = variable, importance)

ImmuneGO_Genes = all_degs_p_05_vac_infected_19_12_23 %>% 
  inner_join(rf_genes %>% 
               select(genes) %>% 
               distinct() %>% 
               select(genes),
               by = "genes") %>% 
  distinct()

####### INPUT
data_2 = ImmuneGO_Genes
filename_2 = paste0("RandomForest_ImmuneGO_Genes", outcomevar)

######## Matrix
matrix = data_2 %>% 
  select(genes, condition, log2fold_change) %>%
  pivot_wider(names_from = "condition", 
              values_from = "log2fold_change", 
              values_fn = mean) %>% 
  replace(is.na(.), 0) %>%
  arrange(genes) %>% 
  column_to_rownames(var="genes") %>% 
  as.matrix()

######## Annotations
ann_vaccines_covid_other_2 = data_2 %>% 
  select(condition, disease_vac, type, week) %>% 
  distinct()

#Columns
ann_cols_heatmap = matrix %>% 
  colnames() %>% 
  data.frame() %>% 
  filter(. != "genes") %>% 
  rename(condition = '.') %>% 
  inner_join(ann_vaccines_covid_other_2, by = "condition") %>% 
  distinct() %>% 
  arrange(condition) %>% 
  column_to_rownames("condition")

matrix_data = matrix %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column(var= "condition") %>% 
  inner_join(ann_cols_heatmap %>% rownames_to_column("condition"), by = "condition") %>% 
  select(!c(disease_vac:week)) %>% 
  arrange(condition) %>% 
  column_to_rownames("condition") %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate_if(is.character, as.numeric) %>%
  as.matrix() 

#Rows Immune ----
ann_rows_immune = matrix_data %>%
  as.data.frame() %>%
  rownames_to_column("genes") %>%
  left_join(ImmuneGO_Annotated_Genes %>% filter(go_term == "Manual"), by = "genes") %>%
  select(genes, process) %>%
  distinct() %>%
  group_by(genes) %>%
  arrange(genes, factor(process, levels = c("INNATE IMMUNE SYSTEM", "ADAPTIVE IMMUNE SYSTEM")), .by_group = TRUE) %>%
  mutate(i_process = row_number()) %>%
  pivot_wider(., names_from = "i_process", values_from = "process") %>%
  column_to_rownames("genes") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("index") %>%
  mutate(index = as.numeric(index)) %>%
  arrange(desc(index)) %>%
  column_to_rownames("index") %>%
  t() %>%
  as.data.frame() %>%
  replace(is.na(.), ".") %>% 
  mutate(`1` = if_else(`1` == ".", "INNATE IMMUNE SYSTEM", `1`))

#Verificar dimensões do dataset
dim(matrix)
dim(matrix_data)
dim(ann_cols_heatmap)
dim(ann_rows_immune)



################# Immune 
#Heatmap annotation
ha = HeatmapAnnotation(df = ann_cols_heatmap, 
                       col = ann_vaxsig_colors,
                       annotation_name_side = "right")

row_ha = HeatmapAnnotation(df = ann_rows_immune,
                       col = col_process_immune,
                       which= "row",
                       show_annotation_name = F,
                       show_legend = F)

# Values colors
col_fun <- colorRamp2(c(-2, 0, 2), c("#9bc1bc", "white", "#ed6a5a"))

file = filename_2
mat = matrix_data
width_image = 30
height_image = 10
width = unit(15, "cm")
height = unit(5, "cm")
column_names_gp = gpar(fontsize = 10)
row_names_gp = gpar(fontsize = 10)
rect_gp = gpar(col = "gray80", lwd = 0.5)

fileimageheatmap_grouped = paste0(file, sep ="_", "Complexheatmap.png")

png(file = fileimageheatmap_grouped, 
    width = width_image, 
    height = height_image, 
    units="cm", 
    res=900)

heatmap_plot = Heatmap(mat,
                        top_annotation = ha,
                        left_annotation = row_ha,
                        show_row_names = TRUE,
                        row_names_side = "right",
                        show_heatmap_legend = TRUE,
                        heatmap_legend_param = list(direction = "horizontal"),
                        col = col_fun, #color
                        show_column_names = TRUE,
                        column_title = fileimageheatmap_grouped,
                        column_title_gp = gpar(fontsize = 10, fontface = "bold"),
                        column_names_rot = 45,
                        column_names_gp = column_names_gp,
                        rect_gp = rect_gp,
                        na_col = "white",
                        cluster_rows = TRUE,
                        row_names_gp = row_names_gp,
                        row_dend_width = unit(0, "cm"),
                        row_split = 2,
                        column_split = 4,
                        row_gap = unit(2, "mm"),
                        cluster_columns = TRUE,
                        column_gap = unit(2, "mm"),
                        show_column_dend = F,
                        show_row_dend = F,
                        row_dend_side = "left",
                        column_dend_side = "top",
                        clustering_distance_rows = "euclidean",
                        border = TRUE,
                        width = width,
                        height = height)

heatmap_plot = draw(heatmap_plot, 
     annotation_legend_side = "left", 
     heatmap_legend_side = "left")

dev.off()

```

### Random forest genes in COVID and other vaccines

```{r}




####### INPUT
data_2 = covid_other_immunego_genes %>% 
  inner_join(rf_genes, by = "genes")
filename_2 = paste0("RF_Genes", "_VAX_COVID")

######## Matrix
matrix = data_2 %>% 
  select(genes, condition, regulation_numeric) %>%
  pivot_wider(names_from = "condition", 
              values_from = "regulation_numeric", 
              values_fn = mean) %>% 
  replace(is.na(.), 0) %>%
  arrange(genes) %>% 
  column_to_rownames(var="genes") %>% 
  as.matrix()

######## Annotations
ann_vaccines_covid_other_2 = data_2 %>% 
  inner_join(ann_vaccines_covid_other, by = "condition") %>% 
  select(condition, covid_other, microbe_type, disease_vac, type, week) %>% 
  distinct()

#Columns
ann_cols_heatmap = matrix %>% 
  colnames() %>% 
  data.frame() %>% 
  filter(. != "genes") %>% 
  rename(condition = '.') %>% 
  inner_join(ann_vaccines_covid_other_2, by = "condition") %>% 
  distinct() %>% 
  arrange(condition) %>% 
  column_to_rownames("condition")

matrix_data = matrix %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column(var= "condition") %>% 
  inner_join(ann_cols_heatmap %>% rownames_to_column("condition"), by = "condition") %>% 
  select(!c(covid_other:week)) %>% 
  arrange(condition) %>% 
  column_to_rownames("condition") %>% 
  t() %>% 
  as.data.frame() %>% 
  filter(rowSums(. != 0) > 1) %>% 
  mutate_if(is.character, as.numeric) %>%
  as.matrix() 

#Rows Immune ----
ann_rows_immune = matrix_data %>%
  as.data.frame() %>%
  rownames_to_column("genes") %>%
  left_join(ImmuneGO_Annotated_Genes %>%
              filter(go_term == "Manual",
                     !process %in% c("TCR REPERTOIRE", "BCR REPERTOIRE")), by = "genes") %>%
  select(genes, process) %>%
  distinct() %>%
  group_by(genes) %>%
  arrange(genes, factor(process, levels = c("INNATE IMMUNE SYSTEM", "ADAPTIVE IMMUNE SYSTEM")), .by_group = TRUE) %>%
  mutate(i_process = row_number()) %>%
  pivot_wider(., names_from = "i_process", values_from = "process") %>%
  column_to_rownames("genes") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("index") %>%
  mutate(index = as.numeric(index)) %>%
  arrange(desc(index)) %>%
  column_to_rownames("index") %>%
  t() %>%
  as.data.frame() %>%
  replace(is.na(.), ".")


# Rows Not immune -----
# ann_rows_notimmune = matrix_data %>%
#   as.data.frame() %>%
#   rownames_to_column("genes") %>%
#   left_join(ann_genes %>%
#                select(process = term, genes = symbol, annotation) %>%
#                filter(annotation == "Major process",
#                       process != "Immune system"), by = "genes") %>%
#   select(genes, process) %>%
#   distinct() %>%
#   group_by(genes) %>%
#   mutate(i_process = row_number()) %>%
#   pivot_wider(., names_from = "i_process", values_from = "process") %>%
#   column_to_rownames("genes") %>%
#   t() %>%
#   as.data.frame() %>%
#   rownames_to_column("index") %>%
#   arrange(desc(index)) %>%
#   column_to_rownames("index") %>%
#   t() %>%
#   as.data.frame() %>%
#   replace(is.na(.), ".")


#Verificar dimensões do dataset
dim(matrix_data)
dim(ann_cols_heatmap)
# dim(ann_rows_notimmune)
dim(ann_rows_immune)

```

```{r}
#Heatmap annotation
ha = HeatmapAnnotation(df = ann_cols_heatmap, 
                       col = ann_vaxsig_colors,
                       annotation_name_side = "left")

row_ha = HeatmapAnnotation(df = ann_rows_immune,
                       col = col_process_immune,
                       which= "row",
                       show_annotation_name = F,
                       show_legend = F)

# Values colors
col_fun <- colorRamp2(c(-1, 0, 1), c("#9bc1bc", "white", "#ed6a5a"))

file = filename_2
mat = matrix_data
width_image = 30
height_image = 10
width = unit(5, "cm")
height = unit(2, "cm")
column_names_gp = gpar(fontsize = 10)
row_names_gp = gpar(fontsize = 10)
rect_gp = gpar(col = "gray80", lwd = 0)
row_split = NULL
column_split = NULL


fileimageheatmap_grouped = paste0(file, sep ="_", "Complexheatmap.png")

png(file = fileimageheatmap_grouped, 
    width = width_image, 
    height = height_image, 
    units="cm", 
    res=900)

heatmap_plot = Heatmap(mat,
                        top_annotation = ha,
                        left_annotation = row_ha,
                        show_row_names = TRUE,
                        row_names_side = "right",
                        show_heatmap_legend = TRUE,
                        heatmap_legend_param = list(direction = "horizontal"),
                        col = col_fun, #color
                        show_column_names = TRUE,
                        column_title = fileimageheatmap_grouped,
                        column_title_gp = gpar(fontsize = 10, fontface = "bold"),
                        column_names_rot = 45,
                        column_names_gp = column_names_gp,
                        rect_gp = rect_gp,
                        na_col = "white",
                        cluster_rows = TRUE,
                        row_names_gp = row_names_gp,
                        row_dend_width = unit(5, "cm"),
                        row_split = row_split,
                        column_split = column_split,
                        row_gap = unit(2, "mm"),
                        cluster_columns = TRUE,
                        column_gap = unit(8, "mm"),
                        show_column_dend = F,
                        show_row_dend = F,
                        row_dend_side = "right",
                        column_dend_side = "top",
                        clustering_distance_rows = "euclidean",
                        clustering_distance_columns = "euclidean",
                        border = TRUE,
                        width = width,
                        height = height,
                        use_raster = F)

heatmap_plot = draw(heatmap_plot)

dev.off()

```




