---
title: "PCA"
output: html_notebook
---

# PCA

Tutoriais
<https://www.datacamp.com/tutorial/pca-analysis-r> 
<https://rpkgs.datanovia.com/factoextra/index.html> <http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/114-mca-multiple-correspondence-analysis-in-r-essentials/>
<https://statisticsglobe.com/pca-before-k-means-clustering-r>>

Bibliotecas
```{r}
library(factoextra)
library(caret)
library(stats)
library(ggfortify)
library(ggplot2)
```


# DESeq2 results

```{r}
# Criar um PCA com o p-valor de cada gene 
pca_data <- prcomp(t(assay(dds)))  # Perform PCA on the transposed count or normalized data

# Create a dataframe with PCA components and Timepointf and FirstSecondDosef
pca_df <- data.frame(PC1 = pca_data$x[, 1], PC2 = pca_data$x[, 2],
                     Timepoint = colData(dds)$Timepoint,
                    Vaccines = colData(dds)$Vaccine)

# Plot the PCA using ggplot2
ggplot(pca_df, aes(x = PC1, y = PC2, color = Vaccines, shape = Timepoint)) +
  geom_point(size = 3) +
  labs(title = "Principal component analysis - Vaccine-Timepoint", x = "PC1", y = "PC2") +
  theme_minimal()

#DESeq2 native analysis
vsd <- vst(dds, blind=FALSE)
pcaData = plotPCA(vsd,intgroup=c("Timepoint", "Vaccine"), returnData = TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))

pca_plot = ggplot(pcaData, aes(PC1, PC2, color=Vaccine, shape=Timepoint)) +
  geom_point(size=2) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed() + ggtitle("Principal component analysis - Vaccines and Timepoint")

ggsave(pca_plot, file = "GSE206023_PCA.png")

```



# PCA By sample

### By genes

Padronizar
```{r}
install.packages("janitor")
library(janitor)

#Inputs
degs_allstudies_updown = degs_allstudies_updown_filter %>% 
  select(-ends_with(".y")) %>% 
  rename_all(~sub("\\.x$", "", .)) %>%
  clean_names() %>% 
  rename(lfcse = lfc_se,
         l2fc = log2fold_change) %>% 
  select(- set_size_intervals) %>% 
  group_by(study) %>% 
  select(vaccine, study, gse_id, genes, process, gene_set_short, immune_system, immune_sub_system, immune_tissue, go_term, set_size, everything(), filter) %>% 
  mutate(study = ifelse(study == "ChAd (V2, D2)", "ChAd (V2, D3)", study)) %>% 
  distinct() %>% 
  filter(filter == "p<0.05")

#Salvar
write.csv(degs_allstudies_updown, file = "ImmuneGO_degs_allstudies_updown_filter_p005.csv")
```

Separar processos imunológicos em objetos
```{r}
############## Innate
Immune_GO_innate = ImmuneGO_Annotated_Genes %>%  #250 genes (SetSize)
  filter(process == "INNATE IMMUNE RESPONSE" & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))

Immune_GO_Complement = degs_allstudies_updown %>% #27 genes (SetSize)
  filter(process == "COMPLEMENT ACTIVATION" & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))

Immune_GO_innate_Inflammatory = degs_allstudies_updown %>% #14 genes (SetSize)
  filter(process == "INFLAMMATORY RESPONSE TO ANTIGENIC STIMULUS" & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))

Immune_GO_innate_DendriticCells = degs_allstudies_updown %>% #11 genes (SetSize)
  filter(process %in% c("DENDRITIC CELL CHEMOTAXIS", 
                        "DENDRITIC CELL HOMEOSTASIS", 
                        "DENDRITIC CELL MIGRATION", 
                        "MYELOID DENDRITIC CELL ACTIVATION", 
                        "MYELOID DENDRITIC CELL CHEMOTAXIS", 
                        "MYELOID DENDRITIC CELL DIFFERENTIATION", 
                        "PLASMACYTOID DENDRITIC CELL ACTIVATION", 
                        "PLASMACYTOID DENDRITIC CELL DIFFERENTIATION") & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))


Immune_GO_innate_Macrophages = degs_allstudies_updown %>% 
  filter(process %in% c("MACROPHAGE ACTIVATION", 
                        "MACROPHAGE ACTIVATION INVOLVED IN IMMUNE RESPONSE", 
                        "MACROPHAGE CHEMOTAXIS", 
                        "MACROPHAGE HOMEOSTASIS",
                        "MACROPHAGE MIGRATION") & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))

Immune_GO_innate_APP = degs_allstudies_updown %>% #21 genes (SetSize)
  filter(process == "ANTIGEN PROCESSING AND PRESENTATION" & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))

Immune_GO_innate_TLR = degs_allstudies_updown %>% #14 genes (SetSize)
  filter(process == "TOLL-LIKE RECEPTOR SIGNALING PATHWAY" & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))

Immune_GO_innate_PRR = degs_allstudies_updown %>% #8 genes (SetSize)
  filter(process == "PATTERN RECOGNITION RECEPTOR SIGNALING PATHWAY" & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))
Immune_GO_innate_CPR = degs_allstudies_updown %>% #6 genes (SetSize)
  filter(process == "CYTOSOLIC PATTERN RECOGNITION RECEPTOR SIGNALING PATHWAY" & 
         ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
          (gse_id == "GSE206023" & pvalue <= 0.05)))

############## Adaptive
Immune_GO_adaptive = degs_allstudies_updown %>% #330 genes (SetSize)
  filter(process == "ADAPTIVE IMMUNE RESPONSE" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

#Humoral
Immune_GO_adaptive_humoral = degs_allstudies_updown %>% #27 genes (SetSize)
  filter(process == "HUMORAL ADAPTIVE IMMUNE SYSTEM" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

Immune_GO_adap_IgMediated = degs_allstudies_updown %>% #62 genes (SetSize)
  filter(process == "IMMUNOGLOBULIN MEDIATED IMMUNE RESPONSE" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

Immune_GO_adap_Breceptorsig = degs_allstudies_updown %>% #31 genes (SetSize)
  filter(process == "B CELL RECEPTOR SIGNALING PATHWAY" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

Immune_GO_adap_Bactivation = degs_allstudies_updown %>% #36 genes
  filter(process == "B CELL ACTIVATION" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

#Cellular

Immune_GO_adaptive_cellular = degs_allstudies_updown %>% #41 genes
  filter(process == "CELLULAR ADAPTIVE IMMUNE SYSTEM" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

Immune_GO_adaptive_cellular_tcellactivation = degs_allstudies_updown %>% #41 genes
  filter(process == "T CELL ACTIVATION" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

Immune_GO_adaptive_cellular_treceptor = degs_allstudies_updown %>% #78 genes
  filter(process == "T CELL RECEPTOR SIGNALING PATHWAY" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

Immune_GO_adaptive_cellular_th1 = degs_allstudies_updown %>% #6 genes
  filter(process == "T-HELPER 1 TYPE IMMUNE RESPONSE" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

Immune_GO_adaptive_cellular_th2 = degs_allstudies_updown %>% #5 genes
  filter(process == "TYPE 2 IMMUNE RESPONSE" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))

Immune_GO_adaptive_cellular_th17 = degs_allstudies_updown %>% #3 genes
  filter(process == "T-HELPER 17 TYPE IMMUNE RESPONSE" &
    ((gse_id %in% c("GSE199750", "GSE201533") & padj <= 0.05) |
    (gse_id == "GSE206023" & pvalue <= 0.05)) &
    !(gse_id %in% c("GSE201533")))



ImmuneGO_Genes_interest = bind_rows(
  Immune_GO_general_innate,
  Immune_GO_general_Complement,
  Immune_GO_innate_Inflammatory,
  Immune_GO_innate_Macrophages,
  Immune_GO_innate_DendriticCells,
  Immune_GO_innate_APP,
  Immune_GO_innate_TLR,
  Immune_GO_innate_PRR,
  Immune_GO_innate_CPR,
  Immune_GO_adaptive,
  Immune_GO_adaptive_humoral,
  Immune_GO_adap_IgMediated,
  Immune_GO_adap_Breceptorsig,
  Immune_GO_adap_Bactivation,
  Immune_GO_adaptive_cellular,
  Immune_GO_adaptive_cellular_tcellactivation,
  Immune_GO_adaptive_cellular_treceptor,
  Immune_GO_adaptive_cellular_th1,
  Immune_GO_adaptive_cellular_th2,
  Immune_GO_adaptive_cellular_th17)

write.csv(ImmuneGO_Genes_interest, file = "ImmuneGO_Genes_interest_bystudy.csv")

```

Processar dados
```{r}
# Immune_GO_general_innate
# Immune_GO_adaptive

Immune_GO_general_Complement
Immune_GO_innate_Macrophages
Immune_GO_innate_DendriticCells
Immune_GO_innate_Inflammatory
Immune_GO_innate_APP
Immune_GO_innate_TLR #Não usar
Immune_GO_innate_PRR #(SIGNALING PATHWAY)
Immune_GO_innate_CPR #Não usar
Immune_GO_adaptive_humoral
Immune_GO_adap_IgMediated
Immune_GO_adap_Breceptorsig
Immune_GO_adap_Bactivation
Immune_GO_adaptive_cellular
Immune_GO_adaptive_cellular_tcellactivation
Immune_GO_adaptive_cellular_treceptor


#INPUT
data_genes = Immune_GO_adaptive
filename = "Immune_GO_adaptive"
```

PCA

```{r}
#Converter de long para wide
matrix_genes = data_genes %>% 
  select(study, genes, l2fc) %>%  
  dcast(`study` ~ `genes`, 
        value.var = "l2fc", 
        fun.aggregate = mean) %>% 
  as.data.frame() %>% 
  column_to_rownames(var = "study") %>% 
  replace(is.na(.), 0)

matrix_data_pca = matrix_genes %>% 
  rownames_to_column(var = "Condition")

matrix_data_pca_ready = matrix_data_pca %>% 
  column_to_rownames(var = "Condition")

ann_vaccines_pca_matrix = ann_vaccines_pca %>% 
  merge(matrix_data_pca, 
        by.x = "Condition", 
        all.x = F, 
        all.y = F) %>% 
  select(Condition:Efficacy)

# Verifique quais colunas têm variância muito baixa
nearZeroVarCols <- nearZeroVar(matrix_data_pca_ready, saveMetrics = TRUE)
matrix_data_pca_ready <- matrix_data_pca_ready[, !nearZeroVarCols$nzv]
pca_res <- prcomp(matrix_data_pca_ready, scale. = TRUE)

# Crie o gráfico de PCA
pca_plot_ann = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'Vaccine', 
                    label = 1) + #1: display, 0: hide
  labs(title=filename) +
  theme_classic()
  # scale_color_manual(values = c(BBIBP = "#black", 
  #                               ZF2001 = "black",
  #                               BNT = "#56cfe1",
  #                               ChAd = "#80ffdb" ,
  #                               "ChAd-BNT" = "#72efdd")) 

pca_plot_not_ann = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'Vaccine', 
                    label = 0) + #1: display, 0: hide
  labs(title=filename) +
  theme_classic() +
  stat_ellipse(type = "t")

#Salvar
ggsave(pca_plot_not_ann, filename = paste0(filename, "_PCA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_ann, filename = paste0(filename, "_PCA_ann.png"), width = 10, height = 8)

# Exiba o gráfico
print(pca_plot_ann)
print(pca_plot_not_ann)

############### KNN classification

#Determinar o número de clusters para KNN
pca_scores <- data.frame(pca_res$x[, 1:2])
ggp1 <- fviz_nbclust(pca_scores,  
                     FUNcluster = kmeans,
                     method = "wss")

ggp1 

set.seed(123)                             # Set seed for randomization
kmeans_clust <- kmeans(pca_scores,        # Perform k-means clustering
                        centers = 4) # Definir numero de clusters

#Visualizar clusters
ggp2 <- fviz_pca_ind(pca_res,
                   habillage = kmeans_clust$cluster,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "convex",
                   labelsize = 2) +
     guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "KNN_Clustered.png"))

print(ggp2)
ggsave(ggp2, file = paste0(filename, "KNN_Clustered.png"), width = 5, height = 4)


```


```{r}
########Correlation plot
#Matriz
corr_matrix = cor(matrix_data_pca_ready) 

#Plot
corrplot = ggcorrplot(corr_matrix, hc.order = TRUE) + 
  theme(axis.text.x = element_text(angle = 90, size = 5), 
        axis.text.y = element_text(size = 5))
#Salvar
ggsave(corrplot, file = paste0(filename, "_corrplot.png"), 
       width = 20, #Grande 20, pequeno 10
       height= 20) #Grande 20, pequeno 10
print(corrplot)

#########Scree plot
data.pca = princomp(corr_matrix) #PCA
summary(data.pca) #Retornar PCs

#########Scree plot
scree_plot = fviz_eig(data.pca, 
                      addlabels = TRUE,
                      ylim = c(0, 70)) +
  geom_col(color = "#00AFBB", fill = "#00AFBB") +
  theme_classic()

#Salvar
ggsave(scree_plot, file = paste0(filename, "_screeplot.png"), width = 10, height = 3) 
print(scree_plot)

#Comp1-Comp2
loadings = data.frame(data.pca$loadings[, 1:3])
loadings$Genes = rownames(loadings)
loadings_1 = arrange(loadings, desc(Comp.1))
loadings_2 = arrange(loadings, desc(Comp.2))
loadings_3 = arrange(loadings, desc(Comp.3))

#Plot
loadings_1_plot = ggplot(loadings_1, aes(x = reorder(Genes, -Comp.1), y=Comp.1, fill = Comp.1)) + 
  ggtitle(paste0("Comp1-Comp2 Genes", filename)) + 
  ylab("Comp1") +
  xlab("Genes") +
  geom_bar(stat = "identity") + 
  theme_light() +
  theme(axis.text.x = element_text(vjust = 0.1, hjust = 1, angle = 90, size = 3), 
        axis.text.y = element_text(size = 5),
        plot.title = element_text(size = 15L, hjust = 0.5)) + 
  scale_fill_continuous(type = "viridis") #cores
  
#Salvar
ggsave(loadings_1_plot, 
       file = paste0(filename, "_genescomp1-2.png"), 
       width = 10, height = 5)

print(loadings_1_plot)
```


```{r}
# Graph of the variables
fviz_pca_var_genes = fviz_pca_var(data.pca, 
                                  col.ind = "cos2",
                                  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))

#Salvar
ggsave(fviz_pca_var_genes, file = paste0(filename, "_fviz_pca_var_genes.png"), width = 10)

######### COS2
cos2 = fviz_cos2(data.pca, 
                 choice = "var", 
                 axes = 1:2) + 
  theme(axis.text.x = element_text(angle=45, 
                                   size = 3)) +
  theme_light()

#Salvar
ggsave(cos2, file = paste0(filename, "_cos2.png"), width = 10, height = 5)

#Colorido
fviz_pca_var(data.pca, col.var = "cos2",
            gradient.cols = c("black", "orange", "green"),
            repel = TRUE)

#Print
print(fviz_pca_var_genes)
print(cos2)
```

### By GO term

#### ssGSEA


Preparar dados
```{r}
# Inputs
data = ssgsea_results_unified %>% 
   filter(!is.na(vaccine),
          !process %in% c("INNATE IMMUNE SYSTEM",
                          "ADAPTIVE IMMUNE SYSTEM"))
data_annotation = ann_vaccines_samples %>% 
  mutate(day = as.factor(day),
         week = as.factor(week),
         dose = as.factor(dose),
         disease_vac = if_else(disease_vac == "Healthy", "H", disease_vac)) 
filename = "ssgsea_results_unified"

#Converter de long para wide

#Matriz com anotações
ann_vaccines_pca_matrix = data %>% 
  mutate(qvalue = as.numeric(qvalue)) %>% 
  filter(qvalue < 0.10) %>% 
  select(sample, process, nes) %>% 
  dcast(., `sample` ~ `process`, 
                     value.var = "nes", 
                     fun.aggregate = mean) %>% 
  replace(., . == "NaN", 0) %>% 
  as.data.frame() %>% 
  merge(data_annotation, by.x = "sample", by.y = "sample", all.x = T, all.y = F)


#Matriz para PCA
ann_vaccines_pca_matrix_ready = ann_vaccines_pca_matrix %>%
  select(!condition:previous_vaccination) %>% 
  column_to_rownames("sample")

# Verifique colunas com variancia baixa
nearZeroVarCols <- nearZeroVar(ann_vaccines_pca_matrix_ready, saveMetrics = TRUE)
ann_vaccines_pca_matrix_ready <- ann_vaccines_pca_matrix_ready[, !nearZeroVarCols$nzv]
pca_res <- prcomp(ann_vaccines_pca_matrix_ready, scale. = TRUE)

# Crie o gráfico de PCA
pca_plot = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'vaccine', 
                    label = 0) + 
  theme_minimal() +
  labs(title=filename) +
  theme(panel.grid = element_blank()) +
  scale_fill_continuous(type = "viridis")

# Exiba o gráfico
print(pca_plot)
ggsave(pca_plot, filename = paste0(filename, "_", "PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)

# Crie o gráfico de PCA

###### Condition
pca_plot_condition = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'condition', 
                    label = 0) + 
  theme(panel.grid = element_blank()) +
  labs(title=paste0(filename, "_bycondition")) + #scale fill manual
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  theme(panel.grid = element_blank())

###### Vaccine
pca_plot_vac = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'vaccine', 
                    label = 0) + 
  labs(title=paste0(filename, "_byvaccine")) + #scale fill manual
  scale_color_manual(values = c("BBIBP" = "#dee2e6",
                                "BNT" = "#56cfe1",
                                "ChAd" = "#5e60ce",
                                "ZF2001" = "#b5179e",
                                "MO" = "#D7B0EE",
                                "I" = "#ff4d6d",
                                "H" = "grey95")) +
  theme_minimal() +
  theme(panel.grid = element_blank())

###### Week
pca_plot_week = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'week', 
                    label = 0) + 
  labs(title=paste0(filename, "_week")) + #scale fill manual
  scale_color_manual(values = c("1" = "#caf0f8",
           "2" = "#6CD5EA",
           "3" = "#0087BF",
           "4" = "#015BA0", 
           "7" = "#03045e")) +
  theme_minimal() +
  theme(panel.grid = element_blank())



###### Dose
pca_plot_dose = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'dose', 
                    label = 0) + 
  labs(title=paste0(filename, "_dose")) +
  scale_color_manual(
    values = c("0" = "#caf0f8", 
               "1" = "#56cfe1", 
               "2" = "#5978d4",
               "3" = "#b5179e")) +
  theme_minimal() +
  theme(panel.grid = element_blank())

###### Disease/Vac
pca_plot_disease_vac = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'disease_vac', 
                    label = 0) + 
  labs(title=paste0(filename, "_disease_vac")) +
  scale_color_manual(
    values = c("V" = "#56cfe1", 
               "I" = "#ff4d6d", 
               "H" = "#caf0f8")) +
  theme_minimal() +
  theme(panel.grid = element_blank())

# Exiba o gráfico
print(pca_plot_condition)
print(pca_plot_week)
print(pca_plot_dose)
print(pca_plot_vac)
print(pca_plot_disease_vac)

ggsave(pca_plot_condition, filename = paste0(filename, "CONDITION_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_vac, filename = paste0(filename, "_VACCINE_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_week, filename = paste0(filename, "_WEEK_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_dose, filename = paste0(filename, "_DOSE_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_disease_vac, filename = paste0(filename, "_VAC_INFEC_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)

```


```{r}
############### KNN classification

#Determinar o número de clusters para KNN
pca_scores <- data.frame(pca_res$x[, 1:2])
fviz_nbclust(pca_scores,  
                     FUNcluster = kmeans,
                     method = "wss")

set.seed(666)                             # Set seed for randomization
kmeans_clust <- kmeans(pca_scores,        # Perform k-means clustering
                        centers = 3) # Definir numero de clusters

#Visualizar clusters
ggp2 <- fviz_pca_ind(pca_res,
                   habillage = kmeans_clust$cluster,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "t",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())

print(ggp2)

ggsave(ggp2, file = paste0(filename, "_KNN_Clustered.png"), width = 5, height = 4)


# Clusterizar por grupo

#Vaccine
pca_group_vac <- fviz_pca_ind(pca_res,
                   habillage = ann_vaccines_pca_matrix$vaccine,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "t",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_Vac_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())

#Dose
pca_group_dose <- fviz_pca_ind(pca_res,
                   habillage = ann_vaccines_pca_matrix$dose,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "t",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_Dose_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())

#Week
pca_group_week <- fviz_pca_ind(pca_res,
                   habillage = ann_vaccines_pca_matrix$week,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "t",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_WEEK_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())


#Day
pca_group_disease_vac <- fviz_pca_ind(pca_res,
                   habillage = ann_vaccines_pca_matrix$disease_vac,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "t",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_Disease_Vac_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())


#Salvar
ggsave(pca_group_week, file = paste0(filename, "_Week_Clustered.png"), width = 5, height = 4)
ggsave(pca_group_dose, file = paste0(filename, "_Dose_Clustered.png"), width = 5, height = 4)
ggsave(pca_group_vac, file = paste0(filename, "_Vac_Clustered.png"), width = 5, height = 4)
ggsave(pca_group_disease_vac, file = paste0(filename, "_INFEC-Vac_Clustered.png"), width = 5, height = 4)
```


```{r}
#Biplot
biplot = fviz_pca_biplot(pca_res,              # Visualize clusters in biplot
                      col.var = "black",
                      alpha.var = 0.5,
                      habillage = kmeans_clust$cluster,
                      repel = TRUE,
                      addEllipses = TRUE,
                      ellipse.type = "convex",
                      labelsize = 3,
                      label = "var",
                      palette = "Set1")

biplot
ggsave(biplot, file = paste0(filename, "_BIPLOT_KNN_Clustered.png"), width = 10, height = 8)
```


```{r}
########Correlation plot
corr_matrix = cor(ann_vaccines_pca_matrix_ready) 

#Plot
corrplot = ggcorrplot(corr_matrix, hc.order = TRUE) + 
  theme(axis.text.x = element_text(angle = 90, size = 5), 
        axis.text.y = element_text(size = 5))
#Salvar
ggsave(corrplot, file = paste0(filename, "_corrplot.png"), 
       width = 4, #Grande 20, pequeno 10
       height= 4) #Grande 20, pequeno 10
print(corrplot)
data.pca <- princomp(corr_matrix) #PCA
summary(data.pca) #Retornar PCs


#########Scree plot
data.pca = princomp(corr_matrix) #PCA
summary(data.pca) #Retornar PCs

#########Scree plot
scree_plot = fviz_eig(data.pca, 
                      addlabels = TRUE,
                      ylim = c(0, 70)) +
  geom_col(color = "#00AFBB", fill = "#00AFBB") +
  theme_classic()

#Salvar
ggsave(scree_plot, file = paste0(filename, "_GSEA_screeplot.png"), width = 10, height = 3) 
print(scree_plot)


#Scree plot
loadings = data.frame(data.pca$loadings[, 1:3])
loadings$Process = rownames(loadings)
loadings_1 = arrange(loadings, desc(Comp.1))
loadings_2 = arrange(loadings, desc(Comp.2))
loadings_3 = arrange(loadings, desc(Comp.3))

#Plot
loadings_1_plot = ggplot(loadings_1, aes(x = reorder(Genes, -Comp.1), y=Comp.1, fill = Comp.1)) + 
  ggtitle(paste0("Comp1-Comp2 Process_", filename)) + 
  ylab("Comp1") +
  xlab("Gene sets") +
  geom_bar(stat = "identity") + 
  theme_light() +
  theme(axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, size = 8), 
        axis.text.y = element_text(size = 5),
        plot.title = element_text(size = 15L, hjust = 0.5)) + 
  scale_fill_continuous(type = "viridis") #cores

print(loadings_1_plot)


loadings_2_plot = ggplot(loadings_2, aes(x = reorder(Genes, -Comp.2), y=Comp.2, fill = Comp.2)) + 
  ggtitle(paste0("Comp2-Comp3 Process_", filename)) + 
  ylab("Comp2") +
  xlab("Gene sets") +
  geom_bar(stat = "identity") + 
  theme_light() +
  theme(axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, size = 8), 
        axis.text.y = element_text(size = 5),
        plot.title = element_text(size = 15L, hjust = 0.5)) + 
  scale_fill_continuous(type = "viridis") #cores

print(loadings_2_plot)


#Salvar
ggsave(loadings_1_plot, 
       file = paste0(filename, "_GSEA_genescomp1-2.png"), 
       width = 10, height = 5)

#Salvar
ggsave(loadings_2_plot, 
       file = paste0(filename, "_GSEA_genescomp2-3.png"), 
       width = 10, height = 5)


# Graph of the variables
fviz_pca_var_genes = fviz_pca_var(data.pca, 
                                  col.ind = "cos2",
                                  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
fviz_pca_var_genes

ggsave(fviz_pca_var_genes, file = paste0(filename, "_fviz_pca_var_GSEA.png"), width = 10)

cos2.1 = fviz_cos2(data.pca, choice = "var", axes = 1:2)
cos2.2 = fviz_cos2(data.pca, choice = "var", axes = 2:3)

ggsave(cos2.1, file = paste0(filename, "_cos2_GSEA_1.png"), width = 10)
ggsave(cos2.2, file = paste0(filename, "_cos2_GSEA_2.png"), width = 10)

```

#### GSEA total


Preparar dados
```{r}
# Inputs
data = Immune_GO_All %>% 
   filter(!is.na(vaccine))

data_annotation = ann_vaccines %>% 
  mutate(day = as.factor(day),
         dose = as.factor(dose)) 

filename = "Immune_GO_All"

#Converter de long para wide

#Matriz com anotações
ann_vaccines_pca_matrix = data %>% 
  mutate(qvalue = as.numeric(qvalue)) %>% 
  filter(qvalue < 0.10) %>% 
  select(condition, process, nes) %>% 
  dcast(., `condition` ~ `condition`, 
                     value.var = "nes", 
                     fun.aggregate = mean) %>% 
  replace(., . == "NaN", 0) %>% 
  as.data.frame() %>% 
  merge(data_annotation, by = "condition", all.x = T, all.y = F)


#Matriz para PCA
ann_vaccines_pca_matrix_ready = ann_vaccines_pca_matrix %>%
  select(!vaccine:previous_vaccination) %>% 
  column_to_rownames("condition")

# Verifique colunas com variancia baixa
nearZeroVarCols <- nearZeroVar(ann_vaccines_pca_matrix_ready, saveMetrics = TRUE)
ann_vaccines_pca_matrix_ready <- ann_vaccines_pca_matrix_ready[, !nearZeroVarCols$nzv]
pca_res <- prcomp(ann_vaccines_pca_matrix_ready, scale. = T)

# Crie o gráfico de PCA
pca_plot = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'vaccine', 
                    label = 0) + 
  theme_minimal() +
  labs(title=filename) +
  theme(panel.grid = element_blank()) +
  scale_fill_continuous(type = "viridis")

# Exiba o gráfico
print(pca_plot)
ggsave(pca_plot, filename = paste0(filename, "_", "PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)

# Crie o gráfico de PCA

###### Condition
pca_plot_condition = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'condition', 
                    label = 0) + 
  theme(panel.grid = element_blank()) +
  labs(title=paste0(filename, "_bycondition")) + #scale fill manual
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  theme(panel.grid = element_blank())

###### Vaccine
pca_plot_vac = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'vaccine', 
                    label = 0) + 
  labs(title=paste0(filename, "_byvaccine")) + #scale fill manual
  scale_color_manual(values = c("BBIBP" = "#dee2e6",
                                "BNT" = "#56cfe1",
                                "ChAd" = "#5e60ce",
                                "ZF2001" = "#b5179e",
                                "MO" = "#D7B0EE",
                                "I" = "#ff4d6d",
                                "H" = "grey95")) +
  theme_minimal() +
  theme(panel.grid = element_blank())

###### Day
pca_plot_day = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'day', 
                    label = 0) + 
  labs(title=paste0(filename, "_day")) + #scale fill manual
  scale_color_manual(values = c(
    "0" = "white",
    "1" = "#caf0f8",
    "2" = "#ade8f4",
    "3" = "#90e0ef",
    "4" = "#6CD5EA",
    "5" = "#48cae4",
    "6" = "#00b4d8",
    "7" = "#0096c7",
    "10" = "#0087BF",
    "14" = "#0077b6",
    "26" = "#015BA0",
    "28" = "#023e8a",
    "51" = "#03045e")) +
  theme_minimal() +
  theme(panel.grid = element_blank())

###### Dose

pca_plot_dose = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'dose', 
                    label = 0) + 
  labs(title=paste0(filename, "_dose")) +
  scale_color_manual(
    values = c("0" = "#caf0f8", 
               "1" = "#56cfe1", 
               "2" = "#5978d4",
               "3" = "#b5179e")) +
  theme_minimal() +
  theme(panel.grid = element_blank())

# Exiba o gráfico
print(pca_plot_condition)
print(pca_plot_day)
print(pca_plot_dose)
print(pca_plot_vac)

ggsave(pca_plot_condition, filename = paste0(filename, "CONDITION_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_vac, filename = paste0(filename, "_VACCINE_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_day, filename = paste0(filename, "_DAY_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_dose, filename = paste0(filename, "_DOSE_PCA_Immune_GO_GSEA_not-ann.png"), width = 10, height = 8)

```


```{r}
############### KNN classification

#Determinar o número de clusters para KNN
pca_scores <- data.frame(pca_res$x[, 1:2])
fviz_nbclust(pca_scores,  
                     FUNcluster = kmeans,
                     method = "wss")

set.seed(666)                             # Set seed for randomization
kmeans_clust <- kmeans(pca_scores,        # Perform k-means clustering
                        centers = 2) # Definir numero de clusters

#Visualizar clusters
ggp2 <- fviz_pca_ind(pca_res,
                   habillage = kmeans_clust$cluster,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "t",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())

print(ggp2)

ggsave(ggp2, file = paste0(filename, "_KNN_Clustered.png"), width = 5, height = 4)


# Clusterizar por grupo

#Vaccine
pca_group_vac <- fviz_pca_ind(pca_res,
                   habillage = ann_vaccines_pca_matrix$vaccine,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "convex",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_Vac_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())

#Dose
pca_group_dose <- fviz_pca_ind(pca_res,
                   habillage = ann_vaccines_pca_matrix$dose,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "convex",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_Dose_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())

#Day
pca_group_day <- fviz_pca_ind(pca_res,
                   habillage = ann_vaccines_pca_matrix$day,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "convex",
                   label = "none",
                   labelsize = 0) +
  guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "_Day_KNN_Clustered.png")) +
  scale_color_brewer(palette="Set1") +
  theme(panel.grid = element_blank())


print(pca_group_day)
print(pca_group_dose)
print(pca_group_vac)


#Salvar
ggsave(pca_group_day, file = paste0(filename, "_Day_Clustered.png"), width = 5, height = 4)
ggsave(pca_group_dose, file = paste0(filename, "_Dose_Clustered.png"), width = 5, height = 4)
ggsave(pca_group_vac, file = paste0(filename, "_Vac_Clustered.png"), width = 5, height = 4)
```


```{r}
#Biplot
biplot = fviz_pca_biplot(pca_res,              # Visualize clusters in biplot
                      col.var = "black",
                      alpha.var = 0.5,
                      habillage = kmeans_clust$cluster,
                      repel = TRUE,
                      addEllipses = TRUE,
                      ellipse.type = "convex",
                      labelsize = 3,
                      label = "var",
                      palette = "Set1")


ggsave(biplot, file = paste0(filename, "_BIPLOT_KNN_Clustered.png"), width = 10, height = 8)
```


```{r}
########Correlation plot
corr_matrix = cor(ann_vaccines_pca_matrix_ready) 

#Plot
corrplot = ggcorrplot(corr_matrix, hc.order = TRUE) + 
  theme(axis.text.x = element_text(angle = 90, size = 5), 
        axis.text.y = element_text(size = 5))
#Salvar
ggsave(corrplot, file = paste0(filename, "_corrplot.png"), 
       width = 4, #Grande 20, pequeno 10
       height= 4) #Grande 20, pequeno 10
print(corrplot)
data.pca <- princomp(corr_matrix) #PCA
summary(data.pca) #Retornar PCs


#########Scree plot
data.pca = princomp(corr_matrix) #PCA
summary(data.pca) #Retornar PCs

#########Scree plot
scree_plot = fviz_eig(data.pca, 
                      addlabels = TRUE,
                      ylim = c(0, 70)) +
  geom_col(color = "#00AFBB", fill = "#00AFBB") +
  theme_classic()

#Salvar
ggsave(scree_plot, file = paste0(filename, "_GSEA_screeplot.png"), width = 10, height = 3) 
print(scree_plot)


#Scree plot
loadings = data.frame(data.pca$loadings[, 1:3])
loadings$Genes = rownames(loadings)
loadings_1 = arrange(loadings, desc(Comp.1))
loadings_2 = arrange(loadings, desc(Comp.2))
loadings_3 = arrange(loadings, desc(Comp.3))

#Plot
loadings_1_plot = ggplot(loadings_1, aes(x = reorder(Genes, -Comp.1), y=Comp.1, fill = Comp.1)) + 
  ggtitle(paste0("Comp1-Comp2 Genes", filename)) + 
  ylab("Comp1") +
  xlab("Gene sets") +
  geom_bar(stat = "identity") + 
  theme_light() +
  theme(axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, size = 8), 
        axis.text.y = element_text(size = 5),
        plot.title = element_text(size = 15L, hjust = 0.5)) + 
  scale_fill_continuous(type = "viridis") #cores

print(loadings_1_plot)


loadings_2_plot = ggplot(loadings_2, aes(x = reorder(Genes, -Comp.2), y=Comp.2, fill = Comp.2)) + 
  ggtitle(paste0("Comp2-Comp3 Genes_", filename)) + 
  ylab("Comp2") +
  xlab("Gene sets") +
  geom_bar(stat = "identity") + 
  theme_light() +
  theme(axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, size = 8), 
        axis.text.y = element_text(size = 5),
        plot.title = element_text(size = 15L, hjust = 0.5)) + 
  scale_fill_continuous(type = "viridis") #cores

print(loadings_2_plot)


#Salvar
ggsave(loadings_1_plot, 
       file = paste0(filename, "_GSEA_genescomp1-2.png"), 
       width = 10, height = 5)

#Salvar
ggsave(loadings_2_plot, 
       file = paste0(filename, "_GSEA_genescomp2-3.png"), 
       width = 10, height = 5)


# Graph of the variables
fviz_pca_var_genes = fviz_pca_var(data.pca, 
                                  col.ind = "cos2",
                                  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
fviz_pca_var_genes

ggsave(fviz_pca_var_genes, file = paste0(filename, "_fviz_pca_var_GSEA.png"), width = 10)

cos2.1 = fviz_cos2(data.pca, choice = "var", axes = 1:2)
cos2.2 = fviz_cos2(data.pca, choice = "var", axes = 2:3)

ggsave(cos2.1, file = paste0(filename, "_cos2_GSEA_1.png"), width = 10)
ggsave(cos2.2, file = paste0(filename, "_cos2_GSEA_2.png"), width = 10)

```




#### By genes


Processar dados
```{r}
# Immune_GO_general_innate
# Immune_GO_adaptive

#INPUT
data_genes = ssgsea_results_unified
filename = "ssgsea_results_unified"
```

PCA

```{r}
#Converter de long para wide
matrix_genes = data_genes %>% 
  select(study, genes, l2fc) %>%  
  dcast(`study` ~ `genes`, 
        value.var = "l2fc", 
        fun.aggregate = mean) %>% 
  as.data.frame() %>% 
  column_to_rownames(var = "study") %>% 
  replace(is.na(.), 0)

matrix_data_pca = matrix_genes %>% 
  rownames_to_column(var = "Condition")

matrix_data_pca_ready = matrix_data_pca %>% 
  column_to_rownames(var = "Condition")

ann_vaccines_pca_matrix = ann_vaccines_pca %>% 
  merge(matrix_data_pca, 
        by.x = "Condition", 
        all.x = F, 
        all.y = F) %>% 
  select(Condition:Efficacy)

# Verifique quais colunas têm variância muito baixa
nearZeroVarCols <- nearZeroVar(matrix_data_pca_ready, saveMetrics = TRUE)
matrix_data_pca_ready <- matrix_data_pca_ready[, !nearZeroVarCols$nzv]
pca_res <- prcomp(matrix_data_pca_ready, scale. = TRUE)

# Crie o gráfico de PCA
pca_plot_ann = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'Vaccine', 
                    label = 1) + #1: display, 0: hide
  labs(title=filename) +
  theme_classic()
  # scale_color_manual(values = c(BBIBP = "#black", 
  #                               ZF2001 = "black",
  #                               BNT = "#56cfe1",
  #                               ChAd = "#80ffdb" ,
  #                               "ChAd-BNT" = "#72efdd")) 

pca_plot_not_ann = autoplot(pca_res, 
                    data = ann_vaccines_pca_matrix, 
                    colour = 'Vaccine', 
                    label = 0) + #1: display, 0: hide
  labs(title=filename) +
  theme_classic() +
  stat_ellipse(type = "t")

#Salvar
ggsave(pca_plot_not_ann, filename = paste0(filename, "_PCA_not-ann.png"), width = 10, height = 8)
ggsave(pca_plot_ann, filename = paste0(filename, "_PCA_ann.png"), width = 10, height = 8)

# Exiba o gráfico
print(pca_plot_ann)
print(pca_plot_not_ann)

############### KNN classification

#Determinar o número de clusters para KNN
pca_scores <- data.frame(pca_res$x[, 1:2])
ggp1 <- fviz_nbclust(pca_scores,  
                     FUNcluster = kmeans,
                     method = "wss")

ggp1 

set.seed(123)                             # Set seed for randomization
kmeans_clust <- kmeans(pca_scores,        # Perform k-means clustering
                        centers = 4) # Definir numero de clusters

#Visualizar clusters
ggp2 <- fviz_pca_ind(pca_res,
                   habillage = kmeans_clust$cluster,
                   repel = TRUE,
                   addEllipses = TRUE,
                   ellipse.type = "convex",
                   labelsize = 2) +
     guides(color = guide_legend(override.aes = list(label = ""))) +
  ggtitle(paste0(filename,  "KNN_Clustered.png"))

print(ggp2)
ggsave(ggp2, file = paste0(filename, "KNN_Clustered.png"), width = 5, height = 4)


```


```{r}
########Correlation plot
#Matriz
corr_matrix = cor(matrix_data_pca_ready) 

#Plot
corrplot = ggcorrplot(corr_matrix, hc.order = TRUE) + 
  theme(axis.text.x = element_text(angle = 90, size = 5), 
        axis.text.y = element_text(size = 5))
#Salvar
ggsave(corrplot, file = paste0(filename, "_corrplot.png"), 
       width = 20, #Grande 20, pequeno 10
       height= 20) #Grande 20, pequeno 10
print(corrplot)

#########Scree plot
data.pca = princomp(corr_matrix) #PCA
summary(data.pca) #Retornar PCs

#########Scree plot
scree_plot = fviz_eig(data.pca, 
                      addlabels = TRUE,
                      ylim = c(0, 70)) +
  geom_col(color = "#00AFBB", fill = "#00AFBB") +
  theme_classic()

#Salvar
ggsave(scree_plot, file = paste0(filename, "_screeplot.png"), width = 10, height = 3) 
print(scree_plot)

#Comp1-Comp2
loadings = data.frame(data.pca$loadings[, 1:3])
loadings$Genes = rownames(loadings)
loadings_1 = arrange(loadings, desc(Comp.1))
loadings_2 = arrange(loadings, desc(Comp.2))
loadings_3 = arrange(loadings, desc(Comp.3))

#Plot
loadings_1_plot = ggplot(loadings_1, aes(x = reorder(Genes, -Comp.1), y=Comp.1, fill = Comp.1)) + 
  ggtitle(paste0("Comp1-Comp2 Genes", filename)) + 
  ylab("Comp1") +
  xlab("Genes") +
  geom_bar(stat = "identity") + 
  theme_light() +
  theme(axis.text.x = element_text(vjust = 0.1, hjust = 1, angle = 90, size = 3), 
        axis.text.y = element_text(size = 5),
        plot.title = element_text(size = 15L, hjust = 0.5)) + 
  scale_fill_continuous(type = "viridis") #cores
  
#Salvar
ggsave(loadings_1_plot, 
       file = paste0(filename, "_genescomp1-2.png"), 
       width = 10, height = 5)

print(loadings_1_plot)
```


```{r}
# Graph of the variables
fviz_pca_var_genes = fviz_pca_var(data.pca, 
                                  col.ind = "cos2",
                                  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))

#Salvar
ggsave(fviz_pca_var_genes, file = paste0(filename, "_fviz_pca_var_genes.png"), width = 10)

######### COS2
cos2 = fviz_cos2(data.pca, 
                 choice = "var", 
                 axes = 1:2) + 
  theme(axis.text.x = element_text(angle=45, 
                                   size = 3)) +
  theme_light()

#Salvar
ggsave(cos2, file = paste0(filename, "_cos2.png"), width = 10, height = 5)

#Colorido
fviz_pca_var(data.pca, col.var = "cos2",
            gradient.cols = c("black", "orange", "green"),
            repel = TRUE)

#Print
print(fviz_pca_var_genes)
print(cos2)
```

#### Gene counts for most important genes
```{r}

degs_all_updown


```


```{r}
counts_long_ann = all_counts_matrices %>% 
  inner_join(ann_vaccines_samples, by = "sample")

interesting_genes_comp1 = degs_all_updown %>% 
  filter(genes %in% c("TESPA1", "TRAT1", "RC3H1", "HMGB2", "IL18RAP", "CD6", "CD3G", "PLCG1", "BCL6", "TCF7", "ADARB1", "RPL22", "MAP2K6", "STXBP4", "VNN1", "ALOX5", "ETS1", "PPARG", "FCER1A", "SMAD3")) %>% 
  mutate(pca_comp = "Comp1")

interesting_genes_comp2 = degs_all_updown %>% 
  filter(genes %in% c("IFI35", "IDO1", "BATF2", "GBP1", "PML", "IFITM3", "STAT2", "GCH1", "TRIM26", "BST2", "IRF2", "CTSS", "PDIA3", "ADAR", "TAP2", "IRF9", "IL31RA", "TNFSF10", "LILRB1", "STAT1")) %>% 
  mutate(pca_comp = "Comp2")


interesting_genes = bind_rows(interesting_genes_comp1, interesting_genes_comp2) 

write.csv(interesting_genes, file = "interesting_genes_pca.csv")

esquisser(interesting_genes)

#COMP1

plot_comp1 = interesting_genes %>% 
  filter(pca_comp == "Comp1") %>% 
  ggplot() +
  aes(
    x = condition,
    fill = disease_vac,
    weight = log2fold_change
  ) +
  geom_bar() +
  scale_fill_manual(values = c(I = "#5e60ce", V = "#56cfe1")) +
  labs(x = "Conditions",
        y = "Log2-fold change",
        title = "Genes Comp1",
        fill = "Status") +
  coord_flip() +
  theme_minimal() +
   theme(
    plot.title = element_text(size = 20L,face = "bold", hjust = 0.5),
    axis.title.x = element_text(size = 20, vjust = -0.5),
    axis.title.y = element_text(size = 20, hjust = 0.5),
    legend.title = element_text(size = 20),
    legend.text = element_text(size = 15),
    strip.text = element_text(size=15, face = "bold")) +
  facet_wrap(vars(genes), scales = "free_y")
  
  
ggsave(plot_comp1, file = "interesting_genes_pca_comp1.png", width = 20, height = 13)


#COMP2



plot_comp2 = interesting_genes %>% 
  filter(pca_comp == "Comp2") %>% 
  ggplot() +
  aes(
    x = condition,
    fill = disease_vac,
    weight = log2fold_change
  ) +
  geom_bar() +
  scale_fill_manual(values = c(I = "#5e60ce", V = "#56cfe1")) +
  labs(x = "Conditions",
        y = "Log2-fold change",
        title = "Genes Comp1",
        fill = "Status") +
  coord_flip() +
  theme_minimal() +
   theme(
    plot.title = element_text(size = 20L,face = "bold", hjust = 0.5),
    axis.title.x = element_text(size = 20, vjust = -0.5),
    axis.title.y = element_text(size = 20, hjust = 0.5),
    legend.title = element_text(size = 20),
    legend.text = element_text(size = 15),
    strip.text = element_text(size=15, face = "bold")) +
  facet_wrap(vars(genes), scales = "free_y")
  
  
ggsave(plot_comp2, file = "interesting_genes_pca_comp2.png", width = 20, height = 10)


```





# PVCA

```{r}
install.packages("statVisual")
library(pvca)
library(statVisual)

data("esSim")
print(esSim)

# expression data
dat = exprs(esSim) #Counts matrix by sample
print(dim(dat))
print(dat[1:2,])

# create a fake Batch variable
esSim$Batch=c(rep("A", 4), rep("B", 6), rep("C", 10))

# phenotype data
pDat = pData(esSim) #Metadata
print(dim(pDat))
print(pDat[1:2,])


# feature data
fDat = fData(esSim) #Gene annotation
print(dim(fDat))
print(fDat[1:2,])

```


```{r}
#Metadata
ann_vaccines_samples = ann_vaccines_samples_4_12_23 %>% 
  as.data.frame() %>% 
  distinct() %>% 
  mutate(sample_id = sample) %>% 
  column_to_rownames("sample_id")

#Counts matrix
all_counts_matrices_wide = all_counts_matrices %>% 
  pivot_wider(names_from = "sample", values_from = "counts") %>% 
  column_to_rownames("genes")

all_counts_matrices_wide %>% 
  mutate_all(as.numeric)

write.csv(all_counts_matrices_wide, file = "all_counts_matrices_wide.csv")

all_counts_matrices_wide_matrix = all_counts_matrices_wide
```


```{r}
########## EXAMPLE

data(esSim)
print(esSim)

# expression data
dat = exprs(esSim)
print(dim(dat))
print(dat[1:2,])

# create a fake Batch variable
esSim$Batch=c(rep("A", 4), rep("B", 6), rep("C", 10))
# phenotype data
pDat = pData(esSim)
print(dim(pDat))
print(pDat[1:2,])


# feature data
fDat = fData(esSim)
print(dim(fDat))
print(fDat[1:2,])


statVisual(type = 'PVCA',
           clin_data = pData(esSim), 
           clin_subjid = "sid", 
           gene_data = exprs(esSim), 
           batch.factors = c("grp", "Batch"))

PVCA( 
     clin_data = pData(esSim), 
     clin_subjid = "sid", 
     gene_data = exprs(esSim), 
     batch.factors = c("grp", "Batch"))



```
































