---
title: "Random forest"
author: "Wasim Syed"
date: "2024-03-20"
output: html_document
---

```{r}
install.packages("randomForest")
install.packages("caret")

library(randomForest)
library(caret)

{
  set.seed(123)
  customRF <- list(type = "Classification",
                   library = "randomForest",
                   loop = NULL)
  
  customRF$parameters <- data.frame(parameter = c("mtry", "ntree"),
                                    class = rep("numeric", 2),
                                    label = c("mtry", "ntree"))
  
  customRF$grid <- function(x, y, len = NULL, search = "grid") {}
  customRF$fit <- function(x, y, wts, param, lev, last, weights, classProbs) {
    randomForest(x, y,
                 mtry = param$mtry,
                 ntree=param$ntree)
  }
  customRF$predict <- function(modelFit, newdata, preProc = NULL, submodels = NULL)
    predict(modelFit, newdata)
  
  customRF$prob <- function(modelFit, newdata, preProc = NULL, submodels = NULL)
    predict(modelFit, newdata, type = "prob")
  
  customRF$sort <- function(x) x[order(x[,1]),]
  customRF$levels <- function(x) x$classes
}


#INPUT
data_genes = all_matrices_normalized_counts %>% 
  rownames_to_column("genes") %>% 
  inner_join(ImmuneGO_Annotated_Genes %>% select(genes) %>% distinct(), by = "genes") %>% 
  column_to_rownames("genes")
filename = "ImmuneGO_Genes"

RF_data = data_genes %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("sample") %>% 
  inner_join(ann_vaccines_samples %>% select(sample, disease_vac), by = "sample") %>% 
  select(sample, disease_vac, everything()) %>% 
  column_to_rownames("sample") %>% 
  filter(disease_vac != "H", 
         disease_vac != "Healthy") 
  

df_random_forest = RF_data 

table(df_random_forest$disease_vac)

sample(1:nrow(df_random_forest), 370) -> train_all
df_random_forest[ train_all,] -> all_train
df_random_forest[-train_all,] -> all_test

table(all_train$disease_vac)
table(all_test$disease_vac)

ctrl = trainControl(method = 'cv', number = 20, allowParallel = T)

grid = expand.grid(.mtry = c(1:15), 
                   .ntree = c(500,
                              1500,
                              2000,
                              2500))

rfFit = train(disease_vac ~ .,
              method = customRF,
              tuneGrid = grid,
              trControl = ctrl,
              metric = 'Accuracy',
              data = all_train)

rfFit
plot(rfFit)
summary(rfFit)
```


```{r}
vector_RF = ifelse(all_train$disease_vac == 'I', 320, 50)

colnames(all_train) = gsub("-", "", colnames(all_train))
all_train$disease_vac = if_else(all_train$disease_vac == "V", 0, 1)
rf_aab_Pd = randomForest(factor(disease_vac) ~ .,
                         data = all_train, 
                         importance = T,
                         mtry = 4,
                         ntree = 1500,
                         type = 'class',
                         keep.inbag = TRUE)
                         #weights = vector_RF)

importance(rf_aab_Pd, type = 2)

# importance variable 
{ 
  importance(rf_aab_Pd, type = 2, scale= F)
  t = importance(rf_aab_Pd, type = 2) |> data.frame()
  t$var = rownames(t)
  imps = data.frame(var = t$var, imps = t$MeanDecreaseGini/max(t$MeanDecreaseGini))
}

imps = subset(imps, imps  > 0.7)

tiff("random_with_symp1.tiff", units="in", width=6, height=6, res=300)
color = ifelse(imps$imps < 0.6, '< 0.6', 
               ifelse(imps$imps < 0.7, '0.6-0.7', '> 0.7'))
imps |>
  ggplot(aes(imps, x = reorder(var, imps))) +
  coord_flip() +
  geom_point(aes(size = imps, fill = color), colour = "black", shape = 21) +
  labs(x = "Predictors", y = "Importance scores") +
  theme_bw(18)+
  scale_fill_manual(values = c('gray', 'red', 'royalblue'))
dev.off()
# error OOB
{
oob.err.data = data.frame(Trees = rep(1:nrow(rf_aab_Pd$err.rate), 3), 
                          Type = rep(c("OOB","0","1"), each = nrow(rf_aab_Pd$err.rate)),
                          Error = c(rf_aab_Pd$err.rate[,"OOB"],rf_aab_Pd$err.rate[,"0"],rf_aab_Pd$err.rate[,"1"]))
}

tiff("error_rate11.tiff", units="in", width=5, height=4, res=300)
ggplot(data = oob.err.data, aes(x = Trees, y= Error)) +
  geom_line(aes(color = Type)) +
  theme_bw(18) +
  ylim(0,1) +
  scale_color_manual(values = c('gray','orange', 'black'))
dev.off()

# decision tree
library(rpart)
library(rpart.plot)

fit.tree_score = rpart(disease_vac ~ .,
                       data = all_train,
                       method = "class",
                       cp=0.0008,
                       minsplit = 60)
# building tree 
tiff("decision_tree.tiff", units="in", width=4, height=3, res=300)

rpart.plot(fit.tree_score, box.palette = "Blues") # plot decision tree 
dev.off()

# ROC curve
roc_data = data.frame()
target_variables = colnames(RF_data[5:21])
pred_rf_aab = predict(rf_aab_Pd, all_train, type = 'prob')

```

