---
title: "R Notebook"
output: html_notebook
---

## PCA with tidymodels
```{r cache = TRUE}
#### PCA using tidymodels
#Recipe
rec <- recipe(~., data = USArrests)
#Steps
pca_trans <- rec %>%
  step_normalize(all_numeric()) %>%
  step_pca(all_numeric(), num_comp = 3)
#Prep
pca_estimates <- prep(pca_trans, training = USArrests)
#Variable contribution by PC
tidy(pca_estimates, number = 2)
#PC contribution (variance, cum variance, perc variance, cum perc variance)
tidy(pca_estimates, number = 2, type = "variance")
pca_data <- bake(pca_estimates, USArrests)
```

## PCA with PCAtools
```{r fig.height=8, fig.width=10, cache = TRUE}
##### PCA using PCAtools
# BiocManager::install('PCAtools')
# BiocManager::install("airway")
library(PCAtools)

#Matrix (genes, sample)
matrix = ann_vaccines_pca_matrix_ready %>% t()

#Annotation [rownames(sample), columns (other attributes)] Dataframe
metadata = data_annotation %>% 
  mutate(condition = fct_relevel(condition, colnames(matrix))) %>% 
  inner_join(matrix %>% t() %>% as.data.frame() %>% rownames_to_column("condition") %>% select("condition"), 
             by = "condition") %>% 
  column_to_rownames("condition") %>% 
  select(disease_vac, type, vaccine, dose, day, week, regimen, prior_infection, previous_vaccination)

#PCA
p <- pca(mat = matrix, 
         metadata = metadata, 
         removeVar = 0.1)

options(ggrepel.max.overlaps = Inf)
#Plot
biplot(p,labSize = 3, pointSize = 5, 
       colby = 'type',
                 hline = 0, vline = 0,max.overlaps = Inf,
       colkey = ann_vaxsig_colors$type) 

biplot(p,labSize = 3, pointSize = 5, 
       max.overlaps = Inf,
                 hline = 0, vline = 0,
       colby = 'regimen')

biplot(p,labSize = 3, pointSize = 5,
       max.overlaps = Inf,
                 hline = 0, vline = 0,
       colby = 'day', 
       legendPosition = "left", 
       colkey = ann_vaxsig_colors$day)

biplot(p,labSize = 3, pointSize = 5, 
       max.overlaps = Inf,
                 hline = 0, vline = 0,
       colby = 'disease_vac', 
       legendPosition = "left", 
       colkey = ann_vaxsig_colors$disease_vac)

#Screeplot
#Determine optimal number of PCs
horn <- parallelPCA(mat)
elbow <- findElbowPoint(p$variance)
screeplot(p,
          components = getComponents(p, 1:20),
          vline = c(horn$n, elbow)) +
  geom_label(aes(x = horn$n + 1, y = 50,
                 label = 'Horn\'s', vjust = -1, size = 8)) +
  geom_label(aes(x = elbow + 1, y = 50,
                 label = 'Elbow method', vjust = -1, size = 8)) 

#Plot all paired components 
pairsplot(p,
          components = getComponents(p, c(1:5)),
          triangle = T, 
          trianglelabSize = 12,
          hline = 0, vline = 0,
          pointSize = 2,
          gridlines.major = FALSE, 
          gridlines.minor = FALSE,
          colby = 'type',
          colkey = ann_vaxsig_colors$type,
          title = 'Pairs plot', returnPlot = T,
          plotaxes = FALSE) 

#Loadings plot
plotloadings(p, labSize = 3, 
             col = c(low = '#4DBBD5FF', mid = "white", high = '#DC0000FF') )

#Meta variables
eigencorplot(p,
             metavars = colnames(metadata), 
             col = c(low = '#4DBBD5FF', mid = "white", high = '#DC0000FF')) 
```







