library(ggsci)
library("gridExtra")
library("scales")
scale_fill_npg()
pal_npg()

data("diamonds")

p1 <- ggplot(
  subset(diamonds, carat >= 2.2),
  aes(x = table, y = price, colour = cut)
) +
  geom_point(alpha = 0.7) +
  geom_smooth(method = "loess", alpha = 0.05, linewidth = 1, span = 1) +
  theme_bw()

p2 <- ggplot(
  subset(diamonds, carat > 2.2 & depth > 55 & depth < 70),
  aes(x = depth, fill = cut)
) +
  geom_histogram(colour = "black", binwidth = 1, position = "dodge") +
  theme_bw()

p1_npg <- p1 + scale_color_npg()
p2_npg <- p2 + scale_fill_npg()
grid.arrange(p1_npg, p2_npg, ncol = 2)


#Pallete generator
pal_npg("nrc")(9) #Generate pallette
show_col(pal_npg("nrc")(9)) #Visualize colors



# Colors -----------

### VAX SIG DB ----
ann_vaxsig_colors = list(
  type = c("VLP" = "#7E6148FF",
           "LA" =  "#E64B35FF",
           "CONJ" = "#F39B7FFF", 
           'IN'= "#00A087FF", #1st Gen  vaccines
           'VV' = "#3C5488FF", #3rd Gen vaccines
           'RNA' = "#4DBBD5FF",
           'SU' = "#8491B4FF",
           'I'= "#DC0000FF",
           "H" = "grey95"),
  target_pathogen_disease = c('MENINGOCOCCUS'	= "#00A087FF",
                              'PNEUMOCOCCUS'	= "#44C199",
                              'TUBERCULOSIS'	= "#99e2b4",
                              'F TULARENSIS'	= "#4DBBD5FF",
                              'LEISHMANIA'	= "#118ab2",
                              'MALARIA' = "#015BA0",
                              'EBOV'	= "#5e60ce",
                              'HBV'	= "#D7B0EE",
                              'HBV, HAV'	= "#D7B0EE",
                              'HIV'	= "#b5179e",
                              'HPV'	= "#c77dff",
                              'INFLUENZA'	= "#deaaff",
                              'MEASLES'	= "#9d4edd",
                              'MMR'	= "#7b2cbf",
                              'SMALLPOX'	= "#e5b3fe",
                              'VEEV'	= "#ecbcfd",
                              'VZV'	= "#c8b6ff",
                              'YF'	= "#b8c0ff"),
  covid_other = c("COVID" = "#DC0000FF",
                  "OTHER" = "#4DBBD5FF"),
  microbe_type = c("VIRUS" = "#5e60ce",
                   'BACTERIUM' = "#00A087FF",
                   'PARASITE' = "#7E6148FF"),
  
  week = c("0" = "#ECF8FA",
           "1" = "#caf0f8",
           "2" = "#6CD5EA",
           "3" = "#0087BF",
           "4" = "#015BA0", 
           "6" = "#03045e",
           "7" = "#03045e",
           "8" = "#03045e"),
  month = c("1" = "#caf0f8",
            "0" = "#6CD5EA",
            "2" = "#015BA0"),
  vaccine = c("BBIBP" = "#00A087FF",
              "ZF2001" = "#8491B4FF",
              "BNT" = "#4DBBD5FF",
              "MO" = "#72ddf7",
              "ChAd" = "#3C5488FF",
              "I" = "grey95",
              "H" = "grey95"),
  dose = c(
    "0" = "grey95",
    "1" = "#91D1C2A0",
    "2" = "#00A087FF",
    "3" = "#3C5488FF"),
  day = c(
    "0" = "white",
    "1" = "#caf0f8",
    "2" = "#ade8f4",
    "3" = "#90e0ef",
    "4" = "#6CD5EA",
    "5" = "#48cae4",
    "6" = "#00b4d8",
    "7" = "#0096c7",
    "10" = "#0087BF",
    "11" = "#0087BF",
    "14" = "#0077b6",
    "26" = "#015BA0",
    "28" = "#023e8a",
    "51" = "#03045e"),
  infection = c("0" = "white",
                "1" = "#00A087FF",
                "2" = "#3C5488FF"),
  variant = c("None" = "grey95",
              "Beta" = "#00A087FF",
              "Omicron" = "#3C5488FF"),
  severity = c("H" = "grey95",
               "S" = "#DC0000FF",
               "MO" = "#8491B4FF",
               "MI" = "#91D1C2FF",
               "NA" = "grey95"),
  sex = c("Male" = "#4DBBD5FF",
          "Female" = "#E64B35FF",
          "M/F" = "#8491B4FF"),
  disease_vac = c("I" = "#DC0000FF",
                  "V" = "#4DBBD5FF")
)


# Not immune processes -----
col_process_notimmune = list(
  "1" = c("Cellular" = "#3C5488FF",
          "Interspecies interaction" = "#00A087FF",
          "Metabolism" = "#4DBBD5FF",
          "Reg. of BP" = "#E64B35FF",
          "."="white"),
  "2" = c("Cellular" = "#3C5488FF",
          "Interspecies interaction" = "#00A087FF",
          "Metabolism" = "#4DBBD5FF",
          "Reg. of BP" = "#E64B35FF",
          "."="white"),
  "3" = c("Cellular" = "#3C5488FF",
          "Interspecies interaction" = "#00A087FF",
          "Metabolism" = "#4DBBD5FF",
          "Reg. of BP" = "#E64B35FF",
          "."="white"),
  "4" = c("Cellular" = "#3C5488FF",
          "Interspecies interaction" = "#00A087FF",
          "Metabolism" = "#4DBBD5FF",
          "Reg. of BP" = "#E64B35FF",
          "."="white"),
  "5" = c("Cellular" = "#3C5488FF",
          "Interspecies interaction" = "#00A087FF",
          "Metabolism" = "#4DBBD5FF",
          "Reg. of BP" = "#E64B35FF",
          "."="white"))


#Immune processes ------
col_process_immune = list(
  "1" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
          "B CELL" = "#7b2cbf",
          "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
          "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
          "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
          "T CELLS" = "#c77dff",
          "T HELPER CELLS" = "#c77dcc",
          "COMPLEMENT" = "#ffadc7",
          "ANTIVIRAL & IFN" = "#88d4ab",
          "ARPP" = "#14746f",
          "DENDRITIC CELL" = "#036666",
          "EOSINOPHIL" = "#67b99a",
          "INFLAMMATION" = "#99e2b4",
          "INNATE IMMUNE SYSTEM" = "#06d6a0",
          "MAST CELL" = "#56ab91",
          "MONOCYTE" = "#358f80",
          "NEUTROPHIL" = "#78c6a3",
          "NK CELL" = "#469d89",
          "MACROPHAGE" = "#14746f",
          "GENERAL" = "#343a40",
          "ANTIMICROBIAL" = "#48cae4",
          "."="white"),
  "2" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
          "B CELLS" = "#7b2cbf",
          "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
          "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
          "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
          "T CELL" = "#c77dff",
          "T HELPER CELLS" = "#c77dcc",
          "COMPLEMENT" = "#ffadc7",
          "ANTIVIRAL & IFN" = "#88d4ab",
          "ARPP" = "#14746f",
          "DENDRITIC CELL" = "#036666",
          "EOSINOPHIL" = "#67b99a",
          "INFLAMMATION" = "#99e2b4",
          "INNATE IMMUNE SYSTEM" = "#06d6a0",
          "MAST CELL" = "#56ab91",
          "MONOCYTE" = "#358f80",
          "NEUTROPHIL" = "#78c6a3",
          "NK CELL" = "#469d89",
          "MACROPHAGE" = "#14746f",
          "GENERAL" = "#343a40",
          "ANTIMICROBIAL" = "#48cae4",
          "."="white"),
  "3" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
          "B CELL" = "#7b2cbf",
          "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
          "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
          "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
          "T CELL" = "#c77dff",
          "T HELPER CELLS" = "#c77dcc",
          "COMPLEMENT" = "#ffadc7",
          "ANTIVIRAL & IFN" = "#88d4ab",
          "ARPP" = "#14746f",
          "DENDRITIC CELL" = "#036666",
          "EOSINOPHIL" = "#67b99a",
          "INFLAMMATION" = "#99e2b4",
          "INNATE IMMUNE SYSTEM" = "#06d6a0",
          "MAST CELL" = "#56ab91",
          "MONOCYTE" = "#358f80",
          "NEUTROPHIL" = "#78c6a3",
          "NK CELL" = "#469d89",
          "MACROPHAGE" = "#14746f",
          "GENERAL" = "#343a40",
          "ANTIMICROBIAL" = "#48cae4",
          "."="white"),
  "4" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
          "B CELL" = "#7b2cbf",
          "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
          "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
          "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
          "T CELL" = "#c77dff",
          "T HELPER CELLS" = "#c77dcc",
          "COMPLEMENT" = "#ffadc7",
          "ANTIVIRAL & IFN" = "#88d4ab",
          "ARPP" = "#14746f",
          "DENDRITIC CELL" = "#036666",
          "EOSINOPHIL" = "#67b99a",
          "INFLAMMATION" = "#99e2b4",
          "INNATE IMMUNE SYSTEM" = "#06d6a0",
          "MAST CELL" = "#56ab91",
          "MONOCYTE" = "#358f80",
          "NEUTROPHIL" = "#78c6a3",
          "NK CELL" = "#469d89",
          "MACROPHAGE" = "#14746f",
          "GENERAL" = "#343a40",
          "ANTIMICROBIAL" = "#48cae4",
          "."="white"),
  "5" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
          "B CELL" = "#7b2cbf",
          "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
          "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
          "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
          "T CELL" = "#c77dff",
          "T HELPER CELLS" = "#c77dcc",
          "COMPLEMENT" = "#ffadc7",
          "ANTIVIRAL & IFN" = "#88d4ab",
          "ARPP" = "#14746f",
          "DENDRITIC CELL" = "#036666",
          "EOSINOPHIL" = "#67b99a",
          "INFLAMMATION" = "#99e2b4",
          "INNATE IMMUNE SYSTEM" = "#06d6a0",
          "MAST CELL" = "#56ab91",
          "MONOCYTE" = "#358f80",
          "NEUTROPHIL" = "#78c6a3",
          "NK CELL" = "#469d89",
          "MACROPHAGE" = "#14746f",
          "GENERAL" = "#343a40",
          "ANTIMICROBIAL" = "#48cae4",
          "."="white"),
  "6" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
          "B CELL" = "#7b2cbf",
          "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
          "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
          "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
          "T CELL" = "#c77dff",
          "T HELPER CELLS" = "#c77dcc",
          "COMPLEMENT" = "#ffadc7",
          "ANTIVIRAL & IFN" = "#88d4ab",
          "ARPP" = "#14746f",
          "DENDRITIC CELL" = "#036666",
          "EOSINOPHIL" = "#67b99a",
          "INFLAMMATION" = "#99e2b4",
          "INNATE IMMUNE SYSTEM" = "#06d6a0",
          "MAST CELL" = "#56ab91",
          "MONOCYTE" = "#358f80",
          "NEUTROPHIL" = "#78c6a3",
          "NK CELL" = "#469d89",
          "MACROPHAGE" = "#14746f",
          "GENERAL" = "#343a40",
          "ANTIMICROBIAL" = "#48cae4",
          "."="white"),
  "7" =c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
         "B CELL" = "#7b2cbf",
         "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
         "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
         "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
         "T CELL" = "#c77dff",
         "T HELPER CELLS" = "#c77dcc",
         "COMPLEMENT" = "#ffadc7",
         "ANTIVIRAL & IFN" = "#88d4ab",
         "ARPP" = "#14746f",
         "DENDRITIC CELL" = "#036666",
         "EOSINOPHIL" = "#67b99a",
         "INFLAMMATION" = "#99e2b4",
         "INNATE IMMUNE SYSTEM" = "#06d6a0",
         "MAST CELL" = "#56ab91",
         "MONOCYTE" = "#358f80",
         "NEUTROPHIL" = "#78c6a3",
         "NK CELL" = "#469d89",
         "MACROPHAGE" = "#14746f",
         "GENERAL" = "#343a40",
         "ANTIMICROBIAL" = "#48cae4",
         "."="white"),
  "8" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
          "B CELL" = "#7b2cbf",
          "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
          "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
          "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
          "T CELL" = "#c77dff",
          "T HELPER CELLS" = "#c77dcc",
          "COMPLEMENT" = "#ffadc7",
          "ANTIVIRAL & IFN" = "#88d4ab",
          "ARPP" = "#14746f",
          "DENDRITIC CELL" = "#036666",
          "EOSINOPHIL" = "#67b99a",
          "INFLAMMATION" = "#99e2b4",
          "INNATE IMMUNE SYSTEM" = "#06d6a0",
          "MAST CELL" = "#56ab91",
          "MONOCYTE" = "#358f80",
          "NEUTROPHIL" = "#78c6a3",
          "NK CELL" = "#469d89",
          "MACROPHAGE" = "#14746f",
          "GENERAL" = "#343a40",
          "ANTIMICROBIAL" = "#48cae4",
          "."="white"),
  "9" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
          "B CELL" = "#7b2cbf",
          "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
          "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
          "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
          "T CELL" = "#c77dff",
          "T HELPER CELLS" = "#c77dcc",
          "COMPLEMENT" = "#ffadc7",
          "ANTIVIRAL & IFN" = "#88d4ab",
          "ARPP" = "#14746f",
          "DENDRITIC CELL" = "#036666",
          "EOSINOPHIL" = "#67b99a",
          "INFLAMMATION" = "#99e2b4",
          "INNATE IMMUNE SYSTEM" = "#06d6a0",
          "MAST CELL" = "#56ab91",
          "MONOCYTE" = "#358f80",
          "NEUTROPHIL" = "#78c6a3",
          "NK CELL" = "#469d89",
          "MACROPHAGE" = "#14746f",
          "GENERAL" = "#343a40",
          "ANTIMICROBIAL" = "#48cae4",
          "."="white"),
  "10" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
           "B CELL" = "#7b2cbf",
           "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
           "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
           "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
           "T CELL" = "#c77dff",
           "T HELPER CELLS" = "#c77dcc",
           "COMPLEMENT" = "#ffadc7",
           "ANTIVIRAL & IFN" = "#88d4ab",
           "ARPP" = "#14746f",
           "DENDRITIC CELL" = "#036666",
           "EOSINOPHIL" = "#67b99a",
           "INFLAMMATION" = "#99e2b4",
           "INNATE IMMUNE SYSTEM" = "#06d6a0",
           "MAST CELL" = "#56ab91",
           "MONOCYTE" = "#358f80",
           "NEUTROPHIL" = "#78c6a3",
           "NK CELL" = "#469d89",
           "MACROPHAGE" = "#14746f",
           "GENERAL" = "#343a40",
           "ANTIMICROBIAL" = "#48cae4",
           "."="white"),
  "11" = c("ADAPTIVE IMMUNE SYSTEM" = "#6f2dbd",
           "B CELL" = "#7b2cbf",
           "CELLULAR ADAPTIVE IMMUNE SYSTEM" = "#e0aaff",
           "HUMORAL ADAPTIVE IMMUNE SYSTEM" = "#9d4edd",
           "IMMUNOGLOBULIN MEDIATED RESPONSE"= "#5a189a",
           "T CELL" = "#c77dff",
           "T HELPER CELLS" = "#c77dcc",
           "COMPLEMENT" = "#ffadc7",
           "ANTIVIRAL & IFN" = "#88d4ab",
           "ARPP" = "#14746f",
           "DENDRITIC CELL" = "#036666",
           "EOSINOPHIL" = "#67b99a",
           "INFLAMMATION" = "#99e2b4",
           "INNATE IMMUNE SYSTEM" = "#06d6a0",
           "MAST CELL" = "#56ab91",
           "MONOCYTE" = "#358f80",
           "NEUTROPHIL" = "#78c6a3",
           "NK CELL" = "#469d89",
           "MACROPHAGE" = "#14746f",
           "GENERAL" = "#343a40",
           "ANTIMICROBIAL" = "#48cae4",
           "."="white"))


immune_system_colors = c(
  "Innate" = "#faedcd",
  "Adaptive" = "#ffb5a7",
  "General" = "#99d98c",
  "Other" = "#e5e5e5",
  "Complement" = "#7400b8")

immune_subsystem_colors = c(
  "Adaptive" = "#ffb5a7",
  "Cellular" = "#ff758f",
  "Humoral" = "#ff758f",
  "Antibacterial" = "#4895ef",
  "Antifungal" = "#4361ee",
  "Antimicrobial" = "#7400b8",
  "General" = "#99d98c",
  "Antigen presentation" = "#e4c4a5",
  "APC" = "#ccd5ae",
  "Eosinophil" = "#faedcd",
  "Granulocyte" = "#faedcd",
  "Leukocyte" = "#ffb5a7",
  "Neutrophil" = "#ccd5ae",
  "Innate immune response" = "#faedcd",
  "Interferon" = "#a4c3b2",
  "Antiviral" = "#60495a",
  "Pattern recognition receptor" = "#f4f4d5",
  "Natural killer" = "#fedd96",
  "Mucosa" = "#c3dfe0",
  "Erythrocyte" = "#4895ef")
