```{r}
library(tidymodels)
library(purrr)
library(broom)
library(edgeR)
library(MASS)
library(here)
library(tidyverse)
library(ggsci)
library(paletteer)
library(janitor)
library(lme4)
library(emmeans)
library(moderndive)
library(glmmTMB)
# BiocManager::install("apeglm")
library(apeglm)
library(glmmSeq)
library(DESeq2)
library(broom.mixed)
```


# Files
```{r}
all_matrices_counts <- readRDS(here("DGE analysis", "all_matrices_counts.rds"))
all_matrices_counts = all_matrices_counts %>% 
  column_to_rownames("genes")

all_matrices_counts_tpm_normalized <- readRDS(here("DGE analysis", "all_matrices_counts_tpm_normalized.rds"))

ann_vaccines_samples <- read_csv(here("Annotations and metadata", "ann_vaccines_samples.csv"))
ann_vaccines_conditions <- read_csv(here("Annotations and metadata", "ann_vaccines_conditions.csv"))

gse206023_metadata = ann_vaccines_samples %>% 
  filter(gse_id == "GSE206023") %>% 
  mutate(condition = case_when(condition == "BBIBP (V3, D0)" ~ "H (D0)",
                               condition == "ZF2001 (V3, D0)" ~ "H (D0)",.default = condition),
         condition = as.factor(condition),
         condition = fct_relevel(condition, "H (D0)"),
         sex = as_factor(sex),
         participant_id = as_factor(participant_id),
         # age = scale(age, center = T, scale = T)
         ) %>% 
  #Create factors for each individual by group
  group_by(vaccine) %>%
  mutate(ind.n = as.factor(as.numeric(factor(participant_id)))) %>%
  ungroup() %>% 
  arrange(sample)

#Raw counts
raw_counts <- all_matrices_counts %>% 
  dplyr::select(c(gse206023_metadata$sample)) %>% 
  t() %>% 
  as.data.frame() %>% 
   drop_na(.) %>%
  rownames_to_column("sample") %>% 
  inner_join(ann_vaccines_samples %>% dplyr::select(sample, day, condition, participant_id, age, sex),
             by = "sample") %>% 
  dplyr::select(sample, condition, day, participant_id, age, sex, everything()) %>% 
  column_to_rownames("sample")

#Raw counts with other variables
counts <- all_matrices_counts %>% 
  dplyr::select(c(gse206023_metadata$sample)) %>% 
  t() %>% 
  as.data.frame() %>% 
   drop_na(.) %>%
  rownames_to_column("sample") %>% 
  inner_join(ann_vaccines_samples %>% dplyr::select(sample, vaccine, day, condition, participant_id, age, sex),
             by = "sample") %>% 
  dplyr::select(sample, condition, vaccine, day, participant_id, age, sex, everything()) %>% 
  column_to_rownames("sample") %>% 
  mutate(day = as.factor(day))

# Variance stabilization for TPM counts
counts_tpm <- all_matrices_counts_tpm_normalized %>% 
  dplyr::select(c(gse206023_metadata$sample)) %>% 
  t() %>% 
  as.data.frame() %>% 
  drop_na(.) %>%
  mutate(across(where(is.numeric), ~ log2(.x + 1))) %>% 
  rownames_to_column("sample") %>% 
  inner_join(ann_vaccines_samples %>% dplyr::select(sample, condition, participant_id, age, sex),
             by = "sample") %>% 
  dplyr::select(sample, condition, participant_id, age, sex, everything()) %>% 
  column_to_rownames("sample")



```

#glmmTMB
```{r}
genes <- setdiff(names(raw_counts), c("sex", 
                                      "age", 
                                      "condition"
                                      # "participant_id"
                                      ))

results <- lapply(genes, function(gene) {
  modelo <- glmmTMB(as.formula(paste(gene, "~ sex + age + condition ")), 
                    family = nbinom2, data = raw_counts)
  tidy(modelo)
})

names(results) <- genes
resultados_df <- bind_rows(results, .id = "Gene")

```


```{r}

modelo_nb <- glm.nb(formula = condition ~ tempo * vacina + sexo + idade,
  data = counts_tpm
)

summary(modelo_nb)  # Ver os coeficientes (log2FC)


# Criar função para rodar GLM por gene
ajustar_glm <- function(gene) {
  modelo <- modelo_glm %>%
    fit(as.formula(paste(gene, "~ tempo * vacina + sexo + idade")), data = dados_norm)
  
  tidy(modelo) %>% mutate(gene = gene)  # Extrai coeficientes e adiciona nome do gene
}

# Aplicar modelo a cada gene
resultados_glm <- map_dfr(names(dados_norm)[-c(1:2)], ajustar_glm)

resultados_glm <- resultados_glm %>%
  mutate(log2FC = estimate / log(2)) %>%  # Converte coeficientes para log2FC
  filter(term == "tempo:vacina")  # Foca na interação tempo * vacina

resultados_glm <- resultados_glm %>%
  mutate(p_adj = p.adjust(p.value, method = "BH"))


genes_significativos <- resultados_glm %>%
  filter(p_adj < 0.05 & abs(log2FC) > 1)  # Usa os mesmos critérios do DESeq2
```


# Visualization
```{r}

# Definir cores para cada vacina
colors_vaccines <- c(
  "BBIBP" = "#E64B35FF",
  "ZF2001" = "#4DBBD5FF"
)

# Criar um vetor nomeado onde cada amostra recebe a cor da vacina correspondente
colors_vaccines_samples <- ann_vaccines_samples %>%
  mutate(color = colors_vaccines[vaccine]) %>%
  dplyr::select(participant_id, color) %>%
  deframe()
```

Sex
```{r}
counts %>% 
  ggplot() +
  aes(x = day, y = TLR4) + 
  geom_point(aes(fill = participant_id), pch = 21,
             alpha = 0.5) +
  geom_line(aes(color = participant_id),
            alpha = 0.5) +
  stat_summary(aes(group = vaccine, color = vaccine), 
               fun.y = mean, 
               geom = "line", 
               size = 2.2, 
               alpha = 1.2, 
               width = 0.25, 
               position = position_dodge(width = 0.3)) +
  stat_summary(aes(group = vaccine, color = vaccine), 
               fun.data = mean_se, geom = "errorbar",
               # size = 3, 
               # alpha = 1.2, 
               # width = 0.25, 
               position = position_dodge(width = 0.3)) +
  stat_summary(aes(group = vaccine, fill = vaccine), 
               fun.y = mean, 
               pch = 21,
               geom = "point", 
               size = 3, 
               alpha = 1.2, 
               width = 0.25, 
               position = position_dodge(width = 0.3)) +
  scale_color_manual(values = c(colors_vaccines_samples, colors_vaccines)) + 
  scale_fill_manual(values = c(colors_vaccines_samples, colors_vaccines)) + 
  # scale_x_continuous(breaks = c(0, 7, 14, 28),
  #                    expand = c(0.01, 0.01)) +
  theme_minimal()+
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 1, color ="black"),
        axis.line.y  = element_line(size = 1, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 1, color ="black"),
        panel.grid.major = element_line(linetype = 2, color = "gray75"),
        panel.grid.minor = element_line(linetype = 2, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"),
        legend.direction = "vertical",
        legend.position = "right") +
  facet_wrap(~sex~vaccine, scales = "free_y")
```





#Modelling

```{r}
#Filter genes
genes_filtered = counts %>%
  dplyr::select(!condition:sex) %>%
  filter(rowMeans(across(everything())) > 10)

counts_filtered = counts %>% 
  dplyr::select(condition:sex, colnames(genes_filtered))

```

## Without glmmseq

Poisson distribution
```{r}
modelo_lme2 <- glmer(TLR4 ~ day * vaccine + age + sex + (1 | participant_id), 
                    data = counts,
                    family = poisson)

get_regression_table(modelo_lme2)
summary(modelo_lme2)

pairwise_lme2 = emmeans(modelo_lme2, pairwise ~ day:vaccine, adjust = "BH") 
pairwise_lme2$contrasts %>% 
  as_data_frame() %>% 
  filter(str_starts(contrast, "day0"),
         str_detect(contrast, "BBIBP.*BBIBP|ZF2001.*ZF2001")) %>% 
  mutate(padj = p.adjust(p.value, "BH"),
         log2fc = estimate / log2(exp(1)))
```

Negative-binomial
```{r}
modelo <- glmmTMB(TLR4 ~ day * vaccine + sex + age + (day | participant_id), 
                  data = counts_filtered , family = nbinom2)

summary(modelo)

```

## GLMMSEQ
### Time as factor
```{r}
set.seed(1)
counts_glmmseq = counts_filtered %>% 
  dplyr::select(!condition:sex) %>% 
  t() %>% 
  as.data.frame() %>%
  filter(rowMeans(across(everything())) > 10)

counts_glmmseq = counts_glmmseq %>%
  rownames_to_column("genes") %>%
  slice_sample(n = 100) %>%
  column_to_rownames("genes")

metadata_glmmseq = gse206023_metadata %>%
  mutate(day = as.factor(day)) %>%
  arrange(sample) %>% 
  column_to_rownames("sample")

# Set dispersions
dds <- DESeqDataSetFromMatrix(countData = counts_glmmseq, 
                              colData = metadata_glmmseq, 
                              design = ~ 1)

dds <- DESeq(dds)
dispersions <- setNames(dispersions(dds), rownames(counts_glmmseq))

#Size factors
sizeFactors <- estimateSizeFactorsForMatrix(counts_glmmseq)

#Fit model
results <- glmmSeq(modelFormula = 
                     ~ sex + age + #Fixed-effects
                     vaccine*day + #Fixed-effects interactions
                     (day | participant_id), #Random-effects. Inds respond differently during time
                   countdata = counts_glmmseq,
                   metadata = metadata_glmmseq,
                   dispersion = dispersions, 
                   sizeFactors = sizeFactors, 
                   cores = 8,
                   progress = TRUE)

# #Fit model
# results_lrt <- glmmSeq(~ sex + age + vaccine*day + (1 | participant_id),
#                        reduced = ~ vaccine*day + (1 | participant_id),
#                    countdata = counts_glmmseq,
#                    metadata = metadata_glmmseq,
#                    dispersion = dispersions, 
#                    sizeFactors = sizeFactors,
#                    progress = TRUE)
# 
# summary(results_lrt, "IFI6")


#Assess
stats = summary(results) %>% 
  as.data.frame()

#Get pairwise comparisons
genes = rownames(results@countdata)

emmeans_genes <- function(gene) {
  fit <- glmmRefit(results, gene = gene)  # Ajusta o modelo para um gene específico
  emmeans_fit <- emmeans(fit, pairwise ~ day | vaccine) 
  emmeans_fit = emmeans_fit$contrasts %>% 
    as.data.frame() %>%
    mutate(gene = gene,
            log2fc = estimate / log2(exp(1)))  
  
  return(emmeans_fit)
}

emmeans_results <- map_df(genes, emmeans_genes) %>%
  mutate(p_adj = p.adjust(p.value, method = "BH"))

emmeans_results_filtered = emmeans_results %>% 
  clean_names() %>% 
  filter(str_starts(contrast, "day0")) %>% 
  mutate(l2fc_upper = (estimate + 1.96 * se) / log2(exp(1)),
         l2fc_lower = (estimate - 1.96 * se) / log2(exp(1)),
         estimate_upper = (estimate + 1.96 * se),
         estimate_lower = (estimate - 1.96 * se)) %>% 
  separate(contrast, into = c("day_ref", "day")) %>% 
  mutate(day_ref = str_remove(day_ref, "day"),
         day = str_remove(day, "day"),
         day = fct_relevel(day, c(metadata_glmmseq$day %>% levels()))) %>% 
  dplyr::select(gene, vaccine, day_ref, day, estimate, se, estimate_upper, estimate_lower, log2fc, l2fc_upper, l2fc_lower, everything())

emmeans_results_filtered

emmeans_results_filtered %>% 
  saveRDS(file = here("Notebooks", "Random_effects", "GSE206023_DGE_random_fix_sex-age_interac-dayvaccine_rand-daybyparticipant.rds"))
```

Visualization
```{r}
facetted = emmeans_results_filtered %>% 
  filter(gene == "PAM16") %>% 
  ggplot() +
  aes(x = day,
      y = log2fc,
      color = vaccine,
      fill = vaccine) +
  geom_errorbar(aes(ymin = l2fc_lower, ymax = l2fc_upper), width = 0.1, size = 1,
                position = position_dodge(width = 0.5)) +
  geom_line(aes(group = vaccine), position = position_dodge(width = 0.5)) +
  geom_point(size = 3,
             pch = 21,
             color = "black",
             position = position_dodge(width = 0.5)) +
  geom_hline(yintercept = 0, alpha = 0.5, linetype = 2) +
  theme_minimal() +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "vertical",
        legend.position = "none") +
  facet_grid(~gene~vaccine) +
  labs(x = "Day",
       y = "Log2-fold Change")


together = emmeans_results_filtered %>% 
  filter(gene == "PAM16") %>% 
  ggplot() +
  aes(x = day,
      y = log2fc,
      color = vaccine,
      fill = vaccine) +
  geom_errorbar(aes(ymin = l2fc_lower, ymax = l2fc_upper), width = 0.1, size = 1,
                position = position_dodge(width = 0.5)) +
  geom_line(aes(group = vaccine), position = position_dodge(width = 0.5)) +
    geom_point(size = 3,
             pch = 21,
             color = "black",
             position = position_dodge(width = 0.5)) +
  geom_hline(yintercept = 0, alpha = 0.5, linetype = 2) +
  theme_minimal() +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top") +
  facet_grid(~gene) +
  labs(x = "Day",
       y = "Log2-fold Change",
       fill = "Vaccine",
       color = "Vaccine")

together
facetted

```



```{r}
results_q <- glmmQvals(results)
# labels = c(..)  # Genes to label
plot_fc = fcPlot(results_q, x1var = "day", 
                 x2var = "vaccine", 
                 graphics = "ggplot",
       pCutoff = 0.05, 
       useAdjusted = TRUE,
       # labels = labels,
       colours = c('grey', 'green3', 'gold3', 'blue'))

plot_fc$data

plot_fc
```



### (USE THIS) Time as numeric
```{r}
set.seed(1)
counts_glmmseq = counts_filtered %>% 
  dplyr::select(!condition:sex) %>% 
  t() %>% 
  as.data.frame() %>%
  filter(rowMeans(across(everything())) > 10)

counts_glmmseq = counts_glmmseq %>%
  rownames_to_column("genes") %>%
  slice_sample(n = 100) %>%
  column_to_rownames("genes")

metadata_glmmseq = gse206023_metadata %>%
  # mutate(day = as.factor(day)) %>%
  arrange(sample) %>% 
  column_to_rownames("sample")

# Set dispersions
dds <- DESeqDataSetFromMatrix(countData = counts_glmmseq, 
                              colData = metadata_glmmseq, 
                              design = ~ 1)

dds <- DESeq(dds)
dispersions <- setNames(dispersions(dds), rownames(counts_glmmseq))

#Size factors
sizeFactors <- estimateSizeFactorsForMatrix(counts_glmmseq)

#Fit model
results <- glmmSeq(modelFormula = 
                     ~ sex + age + #Fixed-effects
                     vaccine*day + #Fixed-effects interactions
                     (day | participant_id), #Random-effects. Inds respond differently during time
                   countdata = counts_glmmseq,
                   metadata = metadata_glmmseq,
                   dispersion = dispersions, 
                   sizeFactors = sizeFactors, 
                   cores = 8,
                   progress = TRUE)



#Assess
stats = summary(results) %>% 
  as.data.frame()

# stats %>%
#   saveRDS(file = here("Notebooks", "Random_effects", "GSE206023_DGE_random_fix_sex-age_interac-dayvaccine_rand-daybyparticipant_TimeAsContinuous.rds"))
```

```{r message=FALSE, warning=FALSE}
metadata_modeldata = results@metadata %>% 
    rownames_to_column("sample_id_original") %>%  
  mutate(sample_id = paste("y", sex, age, vaccine, day, sep = "_")) 

counts_original = results@countdata %>% 
  as.data.frame() %>% 
  rownames_to_column("genes") %>% 
  pivot_longer(-genes,
               names_to = "sample_id_original",
               values_to = "counts") %>% 
  inner_join(metadata_modeldata, by = "sample_id_original")

predictions = results@predict %>% 
  as.data.frame() %>% 
  rownames_to_column("genes") %>% 
  pivot_longer(cols = starts_with("y"),
               names_to = "sample_id",
               values_to = "prediction") %>%
  
  mutate(sample_id = str_remove(sample_id, " ")) %>% 
  inner_join(metadata_modeldata, by = "sample_id") %>% 
  dplyr::select(genes, prediction, sample_id) %>% 
  inner_join(counts_original, by = join_by("sample_id", "genes")) %>% 
  inner_join(stats %>% rownames_to_column("genes") %>% 
              dplyr::select(genes, meanExp, "se_vaccineZF2001:day", se_day), 
             by = "genes")

# Plotando expressão ao longo do tempo
predictions %>% 
  filter(genes == "PAM16") %>% 
  ggplot(aes(x = day, y = prediction)) +
  geom_line(aes(group = participant_id), alpha = 0.5, color = "red") + 
  geom_point(aes(y = prediction), position = position_dodge(width = 0.5), color = "red") +
  geom_point(aes(y = prediction), position = position_dodge(width = 0.5), color = "red") +
  geom_point(aes(y = counts), position = position_dodge(width = 0.5), color = "black") +
  geom_line(aes(group = participant_id, y = counts), alpha = 0.5, color = "black") + 
  facet_wrap(~ vaccine) + 
  theme_minimal() +
  scale_x_continuous(breaks = c(0, 7, 14, 28)) +
  labs(y = "Expressão estimada", x = "Dias pós-vacinação",
       subtitle = "Red = Predicted; Black = Actual")
```


```{r message=FALSE, warning=FALSE}
#Fit

fit = glmmRefit(results, gene = "PAM16")  # Ajusta o modelo para um gene específico
emmeans_fit <- emmeans(fit, ~ day | vaccine, 
                       at = list(day = seq(0, 30, by = 1))) %>%
  as_data_frame() %>% 
  mutate(gene = "PAM16")

contrast_day0 = emmeans_fit %>% 
  filter(day == "0") %>% 
  dplyr::select(day, vaccine, emmean_ref = emmean, gene)

emmeans_fit_result = emmeans_fit %>% 
  full_join(contrast_day0, 
             by = join_by(day, vaccine, gene)) %>% 
  fill(emmean_ref, .direction = "down") %>% 
  clean_names() %>% 
  mutate(l2fc = emmean/emmean_ref,
         l2fc = log2(l2fc),
         se_log2 = se / (emmean * log(2)),
         l2fc_upper = (l2fc + 1.96 * se_log2),
         l2fc_lower = (l2fc - 1.96 * se_log2),
         z_score = l2fc / se_log2,
         p_value = 2 * (1 - pnorm(abs(z_score))),
         p_adj = p.adjust(p_value, method = "BH"),
         signif = if_else(p_adj < 0.05, "*", "NS"))



emmeans_fit_result

library(performance)
r2_nakagawa(fit)
```




Visualization
```{r}
facetted = emmeans_fit_result %>% 
  # filter(gene == "PAM16") %>% 
  ggplot() +
  aes(x = day,
      y = l2fc,
      color = vaccine,
      fill = vaccine) +
  geom_errorbar(aes(ymin = l2fc_lower, ymax = l2fc_upper), 
                width = 0.1,
                position = position_dodge(width = 0.5)) +
  geom_line(aes(group = vaccine), position = position_dodge(width = 0.5)) +
  geom_point(aes(shape = signif),
             # pch = 21,
             # color = "black",
             position = position_dodge(width = 0.5)) +
  geom_hline(yintercept = 0, alpha = 0.5, linetype = 2) +
  theme_minimal() +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "vertical",
        legend.position = "top") +
  facet_grid(~gene~vaccine) +
  labs(x = "Day",
       y = "Log2-fold Change")
facetted

together = emmeans_fit_result %>% 
  # filter(gene == "PAM16") %>% 
  ggplot() +
  aes(x = day,
      y = l2fc,
      color = vaccine,
      fill = vaccine) +
  geom_errorbar(aes(ymin = l2fc_lower, ymax = l2fc_upper), width = 0.1, size = 1,
                position = position_dodge(width = 0.5)) +
  geom_line(aes(group = vaccine), position = position_dodge(width = 0.5)) +
    geom_point(size = 3,
             pch = 21,
             color = "black",
             position = position_dodge(width = 0.5)) +
  geom_hline(yintercept = 0, alpha = 0.5, linetype = 2) +
  theme_minimal() +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top") +
  facet_grid(~gene) +
  labs(x = "Day",
       y = "Log2-fold Change",
       fill = "Vaccine",
       color = "Vaccine",
       title = "General Linear Mixed Model",
       subtitle = "~ sex + age + vaccine*day + (day|participant_id)")

together
facetted



```

Avaliar modelo
```{r}

library(plotly)
pred_obs = predictions %>% 
  filter(vaccine == "BBIBP") %>%
  ggplot(aes(x = counts, y = prediction, label = genes)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  theme_minimal() +
  labs(title = "Predições vs. Observações", x = "Predito", y = "Observado")

pred_obs

```




```{r}
fit = glmmRefit(results, gene = "CDC20B") 

newdata <- expand.grid(
  sex = unique(metadata_glmmseq$sex),
  age = mean(metadata_glmmseq$age),
  vaccine = unique(metadata_glmmseq$vaccine),
  day = seq(min(metadata_glmmseq$day), max(metadata_glmmseq$day), length.out = 30),
  participant_id = NA
)


preds_se <- predict(fit, newdata, type = "response", re.form = NA, se.fit = TRUE)
newdata$pred = preds_se$fit
newdata$se_fit = preds_se$se.fit

newdata = newdata %>% 
  mutate(upper = pred + 1.96*se_fit,
         lower = pred - 1.96*se_fit)

pred_obs = predictions %>% 
  filter(genes == "CDC20B") %>% 
  select(genes, counts, prediction, sex, age, vaccine, day)

ggplot(newdata, aes(x = day, y = pred)) +
  geom_line(aes(color = vaccine)) +
  geom_errorbar(aes(ymin = lower, ymax = upper, color = vaccine), 
                  width = 0.1, size = 1,
                position = position_dodge(width = 0.5),) +
  geom_point(aes(x = day, y = counts, fill = vaccine), 
             data = pred_obs,
             size = 2,
             position = position_dodge(width = 1),
                          pch = 21,
             color = "black") +
  geom_point(aes(x = day, y = prediction, color = vaccine), 
             data = pred_obs, 
             pch = 21,
             size = 2,
             fill = NA,
             alpha = 0.5,
             position = position_dodge(width = 1.5)) +
  scale_color_npg() +
  labs(title = "Fitted line, predicted (transparent) and observed (filled)", x = "Day", y = "Counts") +
  # facet_grid(~vaccine) + 
  scale_x_continuous(breaks = c(0, 7, 14, 28)) +
  theme_minimal() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        panel.grid.x = element_line(linetype = 2, color = "gray75"),
        panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top")
```

### Time as numeric, non-linear
```{r}
set.seed(1)
counts_glmmseq = counts_filtered %>% 
  dplyr::select(!condition:sex) %>% 
  t() %>% 
  as.data.frame() %>%
  filter(rowMeans(across(everything())) > 10)

counts_glmmseq = counts_glmmseq %>%
  rownames_to_column("genes") %>%
  slice_sample(n = 100) %>%
  column_to_rownames("genes")

metadata_glmmseq = gse206023_metadata %>%
  # mutate(day = as.factor(day)) %>%
  arrange(sample) %>% 
  column_to_rownames("sample")

# Set dispersions
dds <- DESeqDataSetFromMatrix(countData = counts_glmmseq, 
                              colData = metadata_glmmseq, 
                              design = ~ 1)

dds <- DESeq(dds)
dispersions <- setNames(dispersions(dds), rownames(counts_glmmseq))

#Size factors
sizeFactors <- estimateSizeFactorsForMatrix(counts_glmmseq)


library(gamm4)

#Fit model

counts_meta = counts_glmmseq %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("sample_id") %>% 
  inner_join(metadata_glmmseq %>% 
               select(sample_id,sex, age, day, vaccine, participant_id), by = "sample_id") %>% 
  select(sample_id,sex, age, day, vaccine,participant_id, PAM16) %>% 
  mutate(vaccine = as.factor(vaccine))


counts_meta %>% 
  ggplot() +
  aes(x = day,
      y = PAM16,
      group = participant_id,
      color = vaccine) +
  geom_point() +
  geom_line() +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme_minimal()+
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top") +
  theme(plot.title = element_text(size = 10)) 
  
```

Day as numeric
```{r}
#Day as numeric
dataframe = counts_meta %>%
    select(sex, age, day, vaccine, participant_id, PAM16) %>% 
    filter(vaccine == "ZF2001")

results <- gamm(
  PAM16 ~ s(day, k = 3) + age + sex,
  data = dataframe,
  random = list(participant_id = ~1)
)
summary(results$gam)
# Diagnóstico dos ajustes dos splines
mgcv::gam.check(results$gam)

plot(results$gam, pages = 1, rug = TRUE, shade = TRUE)


# Valores médios e sexo mais comum
pred_data <- expand.grid(
  day = sort(unique(counts_meta$day)),
  age = mean(counts_meta$age, na.rm = TRUE),
  sex = names(sort(table(counts_meta$sex), decreasing = TRUE))[1]
)

# Predição com intervalo de confiança
pred_data$fit <- predict(results$gam, newdata = pred_data, se.fit = TRUE)$fit
pred_data$se <- predict(results$gam, newdata = pred_data, se.fit = TRUE)$se.fit

preds <- predict(results$gam, newdata = pred_data, se.fit = TRUE)

# Intervalo de confiança 95%
pred_data <- pred_data %>%
  mutate(
    lower = fit - 1.96 * se,
    upper = fit + 1.96 * se
  )

gamm_plot = ggplot(pred_data, aes(x = day, y = fit)) +
  geom_line(size = 1.2) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "lightblue", alpha = 0.3) +
  geom_errorbar(aes(ymin = lower, ymax = upper), 
                data = pred_data %>% 
                  filter(day %in% c(0, 7, 14, 28))) +
  labs(
    x = "Day",
    y = "Predicted PAM16 expression",
    title = "Predicted GAMM Fit for PAM16 over Time"
  ) +
  theme_minimal() +
  geom_point(data = counts_meta %>% 
               filter(vaccine == "ZF2001"), 
             mapping = aes(x = day,
              y = PAM16,
              group = participant_id,
              color = vaccine)) +
    theme(legend.position = "none",
        plot.title = element_text(size = 10)) +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top")

gamm_plot
```









All genes
```{r}
df_allgenes <- counts_glmmseq %>%
    as.data.frame() %>%
    rownames_to_column("gene") %>%
    pivot_longer(-gene, names_to = "sample_id", values_to = "value") %>%
    inner_join(metadata_glmmseq, by = "sample_id") %>%
    filter(vaccine == "ZF2001") %>%
    arrange(day) 
df_allgenes
```

Splines interpolation
```{r}

# Supondo que você quer interpolar os valores da vacina ZF2001
df <- counts_glmmseq %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("sample_id") %>% 
  inner_join(metadata_glmmseq %>% 
               select(sample_id,sex, age, day, vaccine, participant_id), by = "sample_id") %>% 
  select(sample_id,sex, age, day, vaccine,participant_id, gene = PAM16) %>% 
  mutate(vaccine = as.factor(vaccine)) %>% 
  filter(vaccine == "ZF2001") %>%
  select(day, gene) %>%
  arrange(day)

# Interpolação com spline base do R
interp <- as.data.frame(spline(x = df$day, y = df$gene, n = 29))

# Renomear colunas para consistência
colnames(interp) <- c("day", "gene_interp")

days = 0:29

# Interpolação spline para média, lower e upper
interp_full <- tibble(
  day = days,
  mean_interp  = spline(df_summary$day, df_summary$mean,  xout = days)$y,
  lower_interp = spline(df_summary$day, df_summary$lower, xout = days)$y,
  upper_interp = spline(df_summary$day, df_summary$upper, xout = days)$y
)


splines_plot = ggplot(interp_full, aes(x = day)) +
  geom_ribbon(aes(ymin = lower_interp, ymax = upper_interp), fill = "lightblue", alpha = 0.3) +
  geom_line(aes(y = mean_interp), color = "black", size = 1.2) +
  labs(
    title = "Spline interpolation: Mean ± 95% CI (0–28 days)",
    x = "Day",
    y = "Interpolated gene expression"
  ) +
  theme_minimal() +
    geom_point(data = counts_meta %>% 
               filter(vaccine == "ZF2001"), 
             mapping = aes(x = day,
              y = PAM16,
              group = participant_id,
              color = vaccine)) +
    geom_errorbar(aes(ymin = lower_interp, ymax = upper_interp), 
                data = interp_full %>% 
                  filter(day %in% c(0, 7, 14, 28))) +
    theme(legend.position = "none",
        plot.title = element_text(size = 10)) +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top") 

splines_plot
```
All genes
```{r}
# Dias interpolados
days <- 0:28

# Genes que você quer processar
genes <- rownames(counts_glmmseq)

# Função para um gene
process_gene <- function(gene_name) {
  df <- counts_glmmseq %>%
    as.data.frame() %>%
    rownames_to_column("gene") %>%
    filter(gene == gene_name) %>%
    pivot_longer(-gene, names_to = "sample_id", values_to = "value") %>%
    select(-gene) %>%
    inner_join(metadata_glmmseq, by = "sample_id") %>%
    filter(vaccine == "ZF2001") %>%
    select(day, value) %>%
    arrange(day)

  # Agrupar por dia para calcular média e SE
  df_summary <- df %>%
    group_by(day) %>%
    summarise(
      mean = mean(value, na.rm = TRUE),
      se = sd(value, na.rm = TRUE) / sqrt(n()),
      lower = mean - 1.96 * se,
      upper = mean + 1.96 * se
    )

  # Spline para média e IC
  interp_full <- tibble(
    day = days,
    mean_interp = spline(df_summary$day, df_summary$mean, xout = days)$y,
    lower_interp = spline(df_summary$day, df_summary$lower, xout = days)$y,
    upper_interp = spline(df_summary$day, df_summary$upper, xout = days)$y,
    gene = gene_name
  )

  return(interp_full)
}

# Aplicar a função a todos os genes
interp_all_genes <- map_dfr(genes, process_gene)


highest_genes = interp_all_genes %>% 
  arrange(-mean_interp) %>% 
  select(gene) %>%  
  distinct() %>% 
  pull() %>% 
  .[1:3]


highest_splines = ggplot(interp_all_genes %>% filter(gene %in% highest_genes), aes(x = day, y = mean_interp)) +
  geom_ribbon(aes(ymin = lower_interp, ymax = upper_interp), fill = "lightblue", alpha = 0.3) +
  geom_line(color = "black", size = 1.2) +
  facet_wrap(~ gene, scales = "free_y") +
  theme_minimal() +
  labs(title = "Spline Interpolation: Mean ± 95% CI", x = "Day", y = "Expression") +
  geom_point(color = "black",
             mapping = aes(x = day, y = value),
             data = df_allgenes %>% 
               filter(gene %in% highest_genes)) +
    geom_errorbar(aes(ymin = lower_interp, ymax = upper_interp), 
                data = interp_all_genes %>% 
                  filter(day %in% c(0, 7, 14, 28),
                          gene %in% highest_genes)) +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top") 
highest_splines
```


Linear interpolation
```{r}
# Interpolação linear para todos os 29 dias
linear_interp <- as.data.frame(approx(x = df$day, y = df$gene, xout = 0:28))

# Renomear colunas
colnames(linear_interp) <- c("day", "gene_interp")

df_summary = df %>%
  group_by(day) %>%
  summarise(
    mean = mean(gene, na.rm = TRUE),
    se = sd(gene, na.rm = TRUE) / sqrt(n()),  # calcula SE
    lower = mean - 1.96 * se,
    upper = mean + 1.96 * se
  )

days = 0:29
# Interpolação linear para média e ICs
interp_full <- tibble(
  day = days,
  mean_interp  = approx(df_summary$day, df_summary$mean,  xout = days)$y,
  lower_interp = approx(df_summary$day, df_summary$lower, xout = days)$y,
  upper_interp = approx(df_summary$day, df_summary$upper, xout = days)$y
)

lines = ggplot(interp_full, aes(x = day)) +
  geom_ribbon(aes(ymin = lower_interp, ymax = upper_interp), fill = "lightblue", alpha = 0.3) +
  geom_line(aes(y = mean_interp), color = "black", size = 1.2) +
  geom_errorbar(aes(ymin = lower_interp, ymax = upper_interp), 
                data = interp_full %>% 
                  filter(day %in% c(0, 7, 14, 28))) +
  labs(
    title = "Interpolated Mean ± 95% CI (0 to 28 days)",
    x = "Day",
    y = "Interpolated gene expression"
  ) +
  theme_minimal() +
    geom_point(data = counts_meta %>% 
               filter(vaccine == "ZF2001"), 
             mapping = aes(x = day,
              y = PAM16,
              group = participant_id,
              color = vaccine)) +
  
  theme(legend.position = "none",
        plot.title = element_text(size = 10)) +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top")
lines

```
All genes
```{r}

# Dias interpolados
days <- 0:28

# Genes que você quer processar
genes <- rownames(counts_glmmseq)

# Função para um gene
process_gene <- function(gene_name) {
  df <- counts_glmmseq %>%
    as.data.frame() %>%
    rownames_to_column("gene") %>%
    filter(gene == gene_name) %>%
    pivot_longer(-gene, names_to = "sample_id", values_to = "value") %>%
    select(-gene) %>%
    inner_join(metadata_glmmseq, by = "sample_id") %>%
    filter(vaccine == "ZF2001") %>%
    select(day, value) %>%
    arrange(day)

  # Agrupar por dia para calcular média e SE
  df_summary <- df %>%
    group_by(day) %>%
    summarise(
      mean = mean(value, na.rm = TRUE),
      se = sd(value, na.rm = TRUE) / sqrt(n()),
      lower = mean - 1.96 * se,
      upper = mean + 1.96 * se
    )

  # Spline para média e IC
  interp_full <- tibble(
    day = days,
    mean_interp = approx(df_summary$day, df_summary$mean, xout = days)$y,
    lower_interp = approx(df_summary$day, df_summary$lower, xout = days)$y,
    upper_interp = approx(df_summary$day, df_summary$upper, xout = days)$y,
    gene = gene_name
  )

  return(interp_full)
}

# Aplicar a função a todos os genes
interp_all_genes <- map_dfr(genes, process_gene)


highest_genes = interp_all_genes %>% 
  arrange(-mean_interp) %>% 
  select(gene) %>%  
  distinct() %>% 
  pull() %>% 
  .[1:3]


highest_lines = ggplot(interp_all_genes %>% filter(gene %in% highest_genes), aes(x = day, y = mean_interp)) +
  geom_ribbon(aes(ymin = lower_interp, ymax = upper_interp), fill = "lightblue", alpha = 0.3) +
  geom_errorbar(aes(ymin = lower_interp, ymax = upper_interp), 
                data = interp_all_genes %>% 
                  filter(day %in% c(0, 7, 14, 28),
                          gene %in% highest_genes)) +
  geom_line(color = "black", size = 1.2) +
  facet_wrap(~ gene, scales = "free_y") +
  theme_minimal() +
  labs(title = "Line Interpolation: Mean ± 95% CI", x = "Day", y = "Expression") +
  geom_point(color = "black",
             mapping = aes(x = day, y = value),
             data = df_allgenes %>% 
               filter(gene %in% highest_genes)) +
  scale_color_aaas() +
  scale_fill_aaas() +
  theme(axis.text = element_text(color = "black", size = 10),
        legend.text = element_text(color = "black", size = 10),
        axis.line.x  = element_line(size = 0.5, color ="black"),
        axis.line.y  = element_line(size = 0.5, color ="black"),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5),
        axis.ticks = element_line(size = 0.5, color ="black"),
        panel.grid.major = element_line(linetype = 0, color = "gray75"),
        panel.grid.minor = element_line(linetype = 0, size = 0, color = "gray75"),
        # panel.grid.x = element_line(linetype = 2, color = "gray75"),
        # panel.grid.y = element_line(linetype = 2, color = "gray75"),
        strip.text = element_text(size = 10, color = "black"), 
        strip.text.y = element_text(size = 10, color = "black", angle = 0), 
        panel.spacing = unit(0, "lines"),
        legend.direction = "horizontal",
        legend.position = "top")

highest_lines

```


PAM16
```{r fig.height=3, fig.width=10}
library(patchwork)
gamm_plot+lines+splines_plot +
  patchwork::plot_layout(axes = "collect")
```

Highest scores
```{r fig.height=5, fig.width=8}
highest_lines/highest_splines +
  patchwork::plot_layout(axes = "collect")
```



